import { MATCH_TIMEZONE, parseMatchKickoff } from "@/lib/match-timezone";

/** FIFA 3-letter codes → ISO 3166-1 alpha-2 for flagcdn (subset used in WC 2026 seed). */
const FIFA_TO_ISO: Record<string, string> = {
  USA: "us",
  MEX: "mx",
  CAN: "ca",
  ARG: "ar",
  BRA: "br",
  ENG: "gb",
  FRA: "fr",
  GER: "de",
  ESP: "es",
  POR: "pt",
  NED: "nl",
  BEL: "be",
  CRO: "hr",
  SUI: "ch",
  POL: "pl",
  JPN: "jp",
  KOR: "kr",
  AUS: "au",
  URU: "uy",
  COL: "co",
  CHI: "cl",
  ECU: "ec",
  PER: "pe",
  CRC: "cr",
  PAN: "pa",
  JAM: "jm",
  HON: "hn",
  SLV: "sv",
  QAT: "qa",
  KSA: "sa",
  IRN: "ir",
  MAR: "ma",
  TUN: "tn",
  EGY: "eg",
  SEN: "sn",
  GHA: "gh",
  NGA: "ng",
  CMR: "cm",
  ALG: "dz",
  RSA: "za",
  CIV: "ci",
  CPV: "cv",
  GAM: "gm",
  GUI: "gn",
  MLI: "ml",
  MTN: "mr",
  NIG: "ne",
  TOG: "tg",
  UGA: "ug",
  ZAM: "zm",
  ZIM: "zw",
  NZL: "nz",
  IDN: "id",
  IRQ: "iq",
  JOR: "jo",
  KUW: "kw",
  LIB: "lb",
  OMA: "om",
  PLE: "ps",
  SYR: "sy",
  UAE: "ae",
  UZB: "uz",
  CHN: "cn",
  IND: "in",
  THA: "th",
  VIE: "vn",
  PHI: "ph",
  MAS: "my",
  SGP: "sg",
  SCO: "gb-sct",
  WAL: "gb-wls",
  UKR: "ua",
  SRB: "rs",
  AUT: "at",
  CZE: "cz",
  DEN: "dk",
  FIN: "fi",
  GRE: "gr",
  HUN: "hu",
  ISL: "is",
  IRL: "ie",
  ITA: "it",
  NOR: "no",
  ROU: "ro",
  SVK: "sk",
  SVN: "si",
  SWE: "se",
  TUR: "tr",
  BIH: "ba",
  MKD: "mk",
  ALB: "al",
  BUL: "bg",
  GEO: "ge",
  KAZ: "kz",
  LVA: "lv",
  LTU: "lt",
  MDA: "md",
  MNE: "me",
  LUX: "lu",
  ARM: "am",
  AZE: "az",
  BLR: "by",
  EST: "ee",
  FRO: "fo",
  GIB: "gi",
  KOS: "xk",
  LIE: "li",
  MLT: "mt",
  SMR: "sm",
  AND: "ad",
  CYP: "cy",
  PAR: "py",
  BOL: "bo",
  VEN: "ve",
  HAI: "ht",
  CUW: "cw",
  TRI: "tt",
  GUA: "gt",
  NCA: "ni",
  BLZ: "bz",
  SUR: "sr",
  GUY: "gy",
  FIJ: "fj",
  TAH: "pf",
  NCL: "nc",
  VAN: "vu",
  SOL: "sb",
  PNG: "pg",
  SAM: "ws",
  TON: "to",
  KIR: "ki",
  TUV: "tv",
  DRC: "cd",
};

export function teamInitials(teamCode: string): string {
  return teamCode.slice(0, 2).toUpperCase();
}

export function teamFlagUrl(teamCode: string): string | null {
  const iso = FIFA_TO_ISO[teamCode.toUpperCase()];
  if (!iso) return null;
  return `https://flagcdn.com/w80/${iso}.png`;
}

export function formatMatchDateTime(
  matchDate: string,
  matchTime: string,
): { dateLabel: string; timeLabel: string } {
  const kickoff = parseMatchKickoff(matchDate, matchTime);

  const dateLabel = new Intl.DateTimeFormat("es-ES", {
    weekday: "long",
    day: "numeric",
    month: "long",
    year: "numeric",
    timeZone: MATCH_TIMEZONE,
  }).format(kickoff);

  const timeLabel = new Intl.DateTimeFormat("es-ES", {
    hour: "2-digit",
    minute: "2-digit",
    hour12: false,
    timeZone: MATCH_TIMEZONE,
  }).format(kickoff);

  return { dateLabel, timeLabel };
}
