-- WC2026 apply-all

-- ===== migrations/20260603000001_initial_schema.sql =====
-- WC 2026 poll engine (ported from Brasil 2014 MySQL → Postgres / Supabase)

-- Catalog
CREATE TABLE public.rounds (
  id_round smallint PRIMARY KEY,
  name_round text NOT NULL UNIQUE
);

CREATE TABLE public.groups (
  id_group smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_code char(1) NOT NULL UNIQUE CHECK (group_code ~ '^[A-L]$')
);

CREATE TABLE public.venues (
  id_venue smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  city text NOT NULL,
  stadium text NOT NULL
);

CREATE TABLE public.teams (
  id_team smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  country text NOT NULL UNIQUE,
  id_group smallint REFERENCES public.groups (id_group),
  code char(3) NOT NULL UNIQUE
);

-- Knockout bracket placeholders (Primero A, Ganador 49, Mejor Tercero X, etc.)
CREATE TABLE public.knockout_slots (
  id_slot smallint PRIMARY KEY,
  label text NOT NULL UNIQUE,
  resolved_team_id smallint REFERENCES public.teams (id_team)
);

-- FIFA third-place combination matrix (fill from official regulations)
CREATE TABLE public.third_place_matrix (
  id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scenario_key text NOT NULL UNIQUE,
  -- which groups supply the 8 best thirds (e.g. 'ABCDEFGH' pattern)
  qualifying_groups text NOT NULL,
  -- JSON map: match_slot -> placeholder label resolved via matrix
  slot_mappings jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE public.matches (
  id_match smallint PRIMARY KEY,
  id_round smallint NOT NULL REFERENCES public.rounds (id_round),
  id_group smallint REFERENCES public.groups (id_group),
  match_date date NOT NULL,
  match_time time NOT NULL,
  id_venue smallint NOT NULL REFERENCES public.venues (id_venue),
  home_team_id smallint NOT NULL REFERENCES public.teams (id_team),
  away_team_id smallint NOT NULL REFERENCES public.teams (id_team),
  home_slot_id smallint REFERENCES public.knockout_slots (id_slot),
  away_slot_id smallint REFERENCES public.knockout_slots (id_slot)
);

CREATE TABLE public.match_results (
  id_match smallint PRIMARY KEY REFERENCES public.matches (id_match) ON DELETE CASCADE,
  goals_home smallint,
  goals_away smallint,
  goals_home_et smallint,
  goals_away_et smallint,
  goals_home_pt smallint,
  goals_away_pt smallint,
  first_goal_minute smallint,
  first_goal_player_id smallint,
  pens_home smallint,
  pens_away smallint
);

CREATE TABLE public.players (
  id_player smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_team smallint NOT NULL REFERENCES public.teams (id_team),
  name text NOT NULL,
  position text,
  club text,
  club_country text
);

-- Scoring weights (was puntos_apuestas)
CREATE TABLE public.scoring_rules (
  id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rule_key text NOT NULL UNIQUE,
  points smallint NOT NULL DEFAULT 0
);

-- User domain (auth.users handled by Supabase Auth)
CREATE TABLE public.profiles (
  id uuid PRIMARY KEY REFERENCES auth.users (id) ON DELETE CASCADE,
  username text UNIQUE,
  first_name text NOT NULL,
  last_name text NOT NULL,
  favorite_team_id smallint REFERENCES public.teams (id_team),
  is_admin boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.pools (
  id_pool smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description text NOT NULL,
  owner_id uuid NOT NULL REFERENCES public.profiles (id) ON DELETE CASCADE,
  is_paid boolean NOT NULL DEFAULT false
);

CREATE TABLE public.predictions (
  id_pool smallint NOT NULL REFERENCES public.pools (id_pool) ON DELETE CASCADE,
  id_match smallint NOT NULL REFERENCES public.matches (id_match) ON DELETE CASCADE,
  goals_home smallint,
  goals_away smallint,
  goals_home_pt smallint,
  goals_away_pt smallint,
  first_goal_minute smallint,
  first_goal_player_id smallint,
  PRIMARY KEY (id_pool, id_match)
);

-- Indexes
CREATE INDEX idx_matches_round ON public.matches (id_round);
CREATE INDEX idx_matches_group ON public.matches (id_group);
CREATE INDEX idx_teams_group ON public.teams (id_group);
CREATE INDEX idx_predictions_match ON public.predictions (id_match);

-- RLS
ALTER TABLE public.rounds ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.venues ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.teams ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.knockout_slots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.third_place_matrix ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.matches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.match_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.players ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.scoring_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pools ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.predictions ENABLE ROW LEVEL SECURITY;

-- Public read for tournament data
CREATE POLICY "Public read rounds" ON public.rounds FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Public read groups" ON public.groups FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Public read venues" ON public.venues FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Public read teams" ON public.teams FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Public read matches" ON public.matches FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Public read match_results" ON public.match_results FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Public read players" ON public.players FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Public read scoring_rules" ON public.scoring_rules FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Public read knockout_slots" ON public.knockout_slots FOR SELECT TO anon, authenticated USING (true);

-- Profiles: own row
CREATE POLICY "Profiles select own" ON public.profiles FOR SELECT TO authenticated USING (auth.uid() = id);
CREATE POLICY "Profiles insert own" ON public.profiles FOR INSERT TO authenticated WITH CHECK (auth.uid() = id);
CREATE POLICY "Profiles update own" ON public.profiles FOR UPDATE TO authenticated USING (auth.uid() = id) WITH CHECK (auth.uid() = id);

-- Pools
CREATE POLICY "Pools select all authenticated" ON public.pools FOR SELECT TO authenticated USING (true);
CREATE POLICY "Pools insert own" ON public.pools FOR INSERT TO authenticated WITH CHECK (owner_id = auth.uid());
CREATE POLICY "Pools update own" ON public.pools FOR UPDATE TO authenticated USING (owner_id = auth.uid()) WITH CHECK (owner_id = auth.uid());

-- Predictions: only pool owner
CREATE POLICY "Predictions select own pool" ON public.predictions FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM public.pools p WHERE p.id_pool = predictions.id_pool AND p.owner_id = auth.uid()));
CREATE POLICY "Predictions insert own pool" ON public.predictions FOR INSERT TO authenticated
  WITH CHECK (EXISTS (SELECT 1 FROM public.pools p WHERE p.id_pool = predictions.id_pool AND p.owner_id = auth.uid()));
CREATE POLICY "Predictions update own pool" ON public.predictions FOR UPDATE TO authenticated
  USING (EXISTS (SELECT 1 FROM public.pools p WHERE p.id_pool = predictions.id_pool AND p.owner_id = auth.uid()))
  WITH CHECK (EXISTS (SELECT 1 FROM public.pools p WHERE p.id_pool = predictions.id_pool AND p.owner_id = auth.uid()));

-- Admin policies (match results, matrix) — service role or is_admin via security definer functions later
CREATE POLICY "Admins manage match_results" ON public.match_results FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM public.profiles pr WHERE pr.id = auth.uid() AND pr.is_admin = true))
  WITH CHECK (EXISTS (SELECT 1 FROM public.profiles pr WHERE pr.id = auth.uid() AND pr.is_admin = true));

CREATE POLICY "Admins manage third_place_matrix" ON public.third_place_matrix FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM public.profiles pr WHERE pr.id = auth.uid() AND pr.is_admin = true))
  WITH CHECK (EXISTS (SELECT 1 FROM public.profiles pr WHERE pr.id = auth.uid() AND pr.is_admin = true));

CREATE POLICY "Public read third_place_matrix" ON public.third_place_matrix FOR SELECT TO anon, authenticated USING (true);

-- ===== migrations/20260603000002_engine_views.sql =====
-- Tournament engine views (2026 format). security_invoker so RLS applies.

-- Core match results with winner logic (from vw_results)
CREATE OR REPLACE VIEW public.v_results
WITH (security_invoker = true) AS
SELECT
  m.id_match,
  m.id_round,
  COALESCE(g.group_code::text, '') AS group_code,
  th.id_team AS home_team_id,
  th.country AS home_country,
  th.code AS home_code,
  ta.id_team AS away_team_id,
  ta.country AS away_country,
  ta.code AS away_code,
  mr.goals_home,
  mr.goals_away,
  mr.goals_home_pt,
  mr.goals_away_pt,
  mr.goals_home_et,
  mr.goals_away_et,
  mr.pens_home,
  mr.pens_away,
  mr.first_goal_minute,
  mr.first_goal_player_id,
  pl.name AS first_goal_player_name,
  CASE WHEN mr.goals_home IS NULL THEN NULL
    WHEN mr.goals_home > mr.goals_away THEN 3
    WHEN mr.goals_home = mr.goals_away THEN 1
    ELSE 0 END AS points_home,
  CASE WHEN mr.goals_away IS NULL THEN NULL
    WHEN mr.goals_home < mr.goals_away THEN 3
    WHEN mr.goals_home = mr.goals_away THEN 1
    ELSE 0 END AS points_away,
  CASE
    WHEN m.id_round = 1 AND mr.goals_home > mr.goals_away THEN th.country
    WHEN m.id_round = 1 AND mr.goals_home = mr.goals_away THEN 'Draw'
    WHEN m.id_round = 1 AND mr.goals_home < mr.goals_away THEN ta.country
    WHEN m.id_round > 1 AND mr.goals_home > mr.goals_away THEN th.country
    WHEN m.id_round > 1 AND mr.goals_home < mr.goals_away THEN ta.country
    WHEN m.id_round > 1 AND mr.goals_home = mr.goals_away THEN
      CASE
        WHEN COALESCE(mr.goals_home_et, 0) > COALESCE(mr.goals_away_et, 0) THEN th.country
        WHEN COALESCE(mr.goals_home_et, 0) < COALESCE(mr.goals_away_et, 0) THEN ta.country
        WHEN COALESCE(mr.goals_home_et, 0) = COALESCE(mr.goals_away_et, 0) THEN
          CASE
            WHEN COALESCE(mr.pens_home, 0) > COALESCE(mr.pens_away, 0) THEN th.country
            WHEN COALESCE(mr.pens_home, 0) < COALESCE(mr.pens_away, 0) THEN ta.country
          END
      END
  END AS winner_country
FROM public.matches m
JOIN public.rounds r ON r.id_round = m.id_round
JOIN public.teams th ON th.id_team = m.home_team_id
JOIN public.teams ta ON ta.id_team = m.away_team_id
LEFT JOIN public.groups g ON g.id_group = m.id_group
LEFT JOIN public.match_results mr ON mr.id_match = m.id_match
LEFT JOIN public.players pl ON pl.id_player = mr.first_goal_player_id;

-- Per-team group stage stats (from vw_results_by_group_tmp chain)
CREATE OR REPLACE VIEW public.v_group_standings_detail
WITH (security_invoker = true) AS
SELECT
  g.group_code,
  t.id_team,
  t.country AS team_name,
  t.code AS team_code,
  COUNT(*) FILTER (WHERE vr.goals_home IS NOT NULL) AS played,
  COUNT(*) FILTER (WHERE
    (vr.home_team_id = t.id_team AND vr.goals_home > vr.goals_away)
    OR (vr.away_team_id = t.id_team AND vr.goals_away > vr.goals_home)) AS wins,
  COUNT(*) FILTER (WHERE vr.goals_home = vr.goals_away AND vr.goals_home IS NOT NULL) AS draws,
  COUNT(*) FILTER (WHERE
    (vr.home_team_id = t.id_team AND vr.goals_home < vr.goals_away)
    OR (vr.away_team_id = t.id_team AND vr.goals_away < vr.goals_home)) AS losses,
  SUM(CASE
    WHEN vr.home_team_id = t.id_team THEN COALESCE(vr.goals_home, 0)
    ELSE COALESCE(vr.goals_away, 0) END) AS goals_for,
  SUM(CASE
    WHEN vr.home_team_id = t.id_team THEN COALESCE(vr.goals_away, 0)
    ELSE COALESCE(vr.goals_home, 0) END) AS goals_against
FROM public.teams t
JOIN public.groups g ON g.id_group = t.id_group
JOIN public.v_results vr ON vr.id_round = 1
  AND (vr.home_team_id = t.id_team OR vr.away_team_id = t.id_team)
GROUP BY g.group_code, t.id_team, t.country, t.code;

CREATE OR REPLACE VIEW public.v_group_standings
WITH (security_invoker = true) AS
SELECT
  group_code,
  id_team,
  team_name,
  team_code,
  played,
  wins,
  draws,
  losses,
  goals_for,
  goals_against,
  goals_for - goals_against AS goal_diff,
  wins * 3 + draws AS points
FROM public.v_group_standings_detail;

-- 1st and 2nd per group (replaces vw_octavos_de_final_uno UNION ALL)
CREATE OR REPLACE VIEW public.v_qualified_top_two
WITH (security_invoker = true) AS
WITH ranked AS (
  SELECT
    gs.*,
    ROW_NUMBER() OVER (
      PARTITION BY gs.group_code
      ORDER BY gs.points DESC, gs.goal_diff DESC, gs.goals_for DESC, gs.id_team
    ) AS pos
  FROM public.v_group_standings gs
)
SELECT
  group_code,
  team_name AS country,
  id_team,
  team_code AS code,
  CASE WHEN pos = 1 THEN 'Primero ' || group_code ELSE 'Segundo ' || group_code END AS slot_label
FROM ranked
WHERE pos <= 2;

-- 8 best third places (new for 2026)
CREATE OR REPLACE VIEW public.v_best_third_places
WITH (security_invoker = true) AS
WITH ranked AS (
  SELECT
    gs.*,
    ROW_NUMBER() OVER (
      PARTITION BY gs.group_code
      ORDER BY gs.points DESC, gs.goal_diff DESC, gs.goals_for DESC, gs.id_team
    ) AS pos
  FROM public.v_group_standings gs
),
thirds AS (
  SELECT * FROM ranked WHERE pos = 3
),
best AS (
  SELECT
    *,
    ROW_NUMBER() OVER (
      ORDER BY points DESC, goal_diff DESC, goals_for DESC, id_team
    ) AS rank_among_thirds
  FROM thirds
)
SELECT
  group_code,
  country,
  id_team,
  code,
  'Mejor Tercero ' || group_code AS slot_label
FROM best
WHERE rank_among_thirds <= 8;

-- All group-phase qualifiers for knockout slot resolution
CREATE OR REPLACE VIEW public.v_group_qualifiers
WITH (security_invoker = true) AS
SELECT group_code, country, id_team, code, slot_label FROM public.v_qualified_top_two
UNION ALL
SELECT group_code, country, id_team, code, slot_label FROM public.v_best_third_places;

-- Fixture with lock window (enabled): 60 min before kickoff (from vw_fixture)
CREATE OR REPLACE VIEW public.v_fixture
WITH (security_invoker = true) AS
SELECT
  m.id_match,
  m.id_round,
  r.name_round,
  COALESCE(g.group_code::text, '') AS group_code,
  TO_CHAR(m.match_date, 'Dy') AS dow,
  m.match_date,
  m.match_time,
  th.code AS home_code,
  th.country AS home_country,
  ta.code AS away_code,
  ta.country AS away_country,
  v.city,
  v.stadium,
  CASE
    WHEN EXTRACT(EPOCH FROM (
      (m.match_date + m.match_time) AT TIME ZONE 'America/New_York' - now()
    )) / 60 < 60 THEN false
    ELSE true
  END AS predictions_open
FROM public.matches m
JOIN public.rounds r ON r.id_round = m.id_round
JOIN public.venues v ON v.id_venue = m.id_venue
JOIN public.teams th ON th.id_team = m.home_team_id
JOIN public.teams ta ON ta.id_team = m.away_team_id
LEFT JOIN public.groups g ON g.id_group = m.id_group;

-- Round of 32 with placeholders resolved to real teams (id_round = 2 in 2026)
CREATE OR REPLACE VIEW public.v_round_of_32_teams
WITH (security_invoker = true) AS
SELECT
  f.id_match,
  f.id_round,
  f.group_code,
  f.match_date,
  f.match_time,
  gq_home.id_team AS home_team_id,
  gq_home.code AS home_code,
  gq_home.country AS home_country,
  gq_away.id_team AS away_team_id,
  gq_away.code AS away_code,
  gq_away.country AS away_country,
  f.city,
  f.stadium,
  f.predictions_open
FROM public.v_fixture f
JOIN public.matches m ON m.id_match = f.id_match
JOIN public.knockout_slots ks_home ON ks_home.id_slot = m.home_slot_id
JOIN public.v_group_qualifiers gq_home ON gq_home.slot_label = ks_home.label
JOIN public.knockout_slots ks_away ON ks_away.id_slot = m.away_slot_id
JOIN public.v_group_qualifiers gq_away ON gq_away.slot_label = ks_away.label
WHERE f.id_round = 2;

GRANT SELECT ON public.v_results TO anon, authenticated;
GRANT SELECT ON public.v_group_standings TO anon, authenticated;
GRANT SELECT ON public.v_qualified_top_two TO anon, authenticated;
GRANT SELECT ON public.v_best_third_places TO anon, authenticated;
GRANT SELECT ON public.v_group_qualifiers TO anon, authenticated;
GRANT SELECT ON public.v_fixture TO anon, authenticated;
GRANT SELECT ON public.v_round_of_32_teams TO anon, authenticated;

-- ===== migrations/20260603000003_seed_catalog.sql =====
-- Catalog seed for WC 2026 structure (teams/fixture to be loaded when draw is final)

INSERT INTO public.rounds (id_round, name_round) VALUES
  (1, 'Fase de Grupos'),
  (2, 'Dieciseisavos de Final'),
  (3, 'Octavos de Final'),
  (4, 'Cuartos de Final'),
  (5, 'Semifinal'),
  (6, 'Tercer Lugar'),
  (7, 'Final')
ON CONFLICT (id_round) DO NOTHING;

INSERT INTO public.groups (group_code) VALUES
  ('A'), ('B'), ('C'), ('D'), ('E'), ('F'),
  ('G'), ('H'), ('I'), ('J'), ('K'), ('L')
ON CONFLICT (group_code) DO NOTHING;

INSERT INTO public.scoring_rules (rule_key, points) VALUES
  ('exact_score', 3),
  ('goal_difference', 2),
  ('winner', 1),
  ('extra_time', 1),
  ('first_goal_minute', 1),
  ('first_goal_scorer', 1)
ON CONFLICT (rule_key) DO NOTHING;

-- Placeholder knockout slots (extend when official bracket is published)
INSERT INTO public.knockout_slots (id_slot, label) VALUES
  (1, 'Primero A'), (2, 'Segundo A'),
  (3, 'Primero B'), (4, 'Segundo B'),
  (5, 'Primero C'), (6, 'Segundo C'),
  (7, 'Primero D'), (8, 'Segundo D'),
  (9, 'Primero E'), (10, 'Segundo E'),
  (11, 'Primero F'), (12, 'Segundo F'),
  (13, 'Primero G'), (14, 'Segundo G'),
  (15, 'Primero H'), (16, 'Segundo H'),
  (17, 'Primero I'), (18, 'Segundo I'),
  (19, 'Primero J'), (20, 'Segundo J'),
  (21, 'Primero K'), (22, 'Segundo K'),
  (23, 'Primero L'), (24, 'Segundo L')
ON CONFLICT (id_slot) DO NOTHING;

-- Third-place matrix: populate from FIFA regulation PDF when combination is known
INSERT INTO public.third_place_matrix (scenario_key, qualifying_groups, slot_mappings)
VALUES ('pending', '', '{}'::jsonb)
ON CONFLICT (scenario_key) DO NOTHING;

-- ===== migrations/20260603000004_auth_profile_trigger.sql =====
-- Auto-create profile on signup (replaces legacy users table insert)
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, first_name, last_name, username)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data ->> 'first_name', ''),
    COALESCE(NEW.raw_user_meta_data ->> 'last_name', ''),
    COALESCE(NEW.raw_user_meta_data ->> 'username', split_part(NEW.email, '@', 1))
  );
  RETURN NEW;
END;
$$;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
