/**
 * Projected WC 2026 squad-style rosters for 48 group-phase nations.
 * Source: FIFA official squads where published; otherwise key national-team
 * players from 2024–2026 cycles (clubs/positions as of early 2026).
 * Regenerate seed: node scripts/generate-players-seed.mjs
 */
export const PLAYER_SQUADS = {
  MEX: [
    ["Guillermo Ochoa", "GK", "Salernitana", "ITA"],
    ["Luis Malagón", "GK", "América", "MEX"],
    ["Jorge Sánchez", "DF", "Ajax", "NED"],
    ["César Montes", "DF", "Almería", "ESP"],
    ["Johan Vásquez", "DF", "Genoa", "ITA"],
    ["Gerardo Arteaga", "DF", "Monterrey", "MEX"],
    ["Luis Chávez", "MF", "Dynamo Moscow", "RUS"],
    ["Edson Álvarez", "MF", "West Ham", "ENG"],
    ["Orbelín Pineda", "MF", "AEK Athens", "GRE"],
    ["Luis Quiñones", "MF", "Tigres", "MEX"],
    ["Carlos Rodríguez", "MF", "Cruz Azul", "MEX"],
    ["Uriel Antuna", "FW", "América", "MEX"],
    ["Raúl Jiménez", "FW", "Fulham", "ENG"],
    ["Santiago Giménez", "FW", "Feyenoord", "NED"],
    ["Alexis Vega", "FW", "Toluca", "MEX"],
    ["Henry Martín", "FW", "América", "MEX"],
    ["Julián Quiñones", "FW", "América", "MEX"],
    ["Roberto Alvarado", "FW", "Guadalajara", "MEX"],
  ],
  RSA: [
    ["Ronwen Williams", "GK", "Mamelodi Sundowns", "RSA"],
    ["Veli Mothwa", "GK", "AmaZulu", "RSA"],
    ["Grant Kekana", "DF", "Mamelodi Sundowns", "RSA"],
    ["Khuliso Mudau", "DF", "Mamelodi Sundowns", "RSA"],
    ["Mothobi Mvala", "DF", "Mamelodi Sundowns", "RSA"],
    ["Austin Ditseke", "DF", "TS Galaxy", "RSA"],
    ["Teboho Mokoena", "MF", "Mamelodi Sundowns", "RSA"],
    ["Sphephelo Sithole", "MF", "AmaZulu", "RSA"],
    ["Thapelo Maseko", "MF", "Mamelodi Sundowns", "RSA"],
    ["Themba Zwane", "MF", "Mamelodi Sundowns", "RSA"],
    ["Percy Tau", "FW", "Al Ahly", "EGY"],
    ["Evidence Makgopa", "FW", "Orlando Pirates", "RSA"],
    ["Zakhele Lepasa", "FW", "Stellenbosch", "RSA"],
    ["Lyle Foster", "FW", "Burnley", "ENG"],
    ["Tashreeq Matthews", "FW", "Cape Town City", "RSA"],
    ["Thapelo Masilela", "MF", "SuperSport United", "RSA"],
    ["Sphelele Mkhulise", "MF", "Mamelodi Sundowns", "RSA"],
    ["Mothusi Maseko", "FW", "SuperSport United", "RSA"],
  ],
  KOR: [
    ["Jo Hyeon-woo", "GK", "Ulsan HD", "KOR"],
    ["Kim Seung-gyu", "GK", "Al-Shabab", "KSA"],
    ["Kim Min-jae", "DF", "Bayern Munich", "GER"],
    ["Kim Young-gwon", "DF", "Ulsan HD", "KOR"],
    ["Jung Seung-hyun", "DF", "Ulsan HD", "KOR"],
    ["Hong Hyun-seok", "MF", "Genk", "BEL"],
    ["Lee Kang-in", "MF", "Paris Saint-Germain", "FRA"],
    ["Hwang In-beom", "MF", "Feyenoord", "NED"],
    ["Paik Seung-ho", "MF", "Birmingham City", "ENG"],
    ["Son Heung-min", "FW", "Tottenham", "ENG"],
    ["Hwang Hee-chan", "FW", "Wolverhampton", "ENG"],
    ["Cho Gue-sung", "FW", "Midtjylland", "DEN"],
    ["Oh Hyeon-gyu", "FW", "Genk", "BEL"],
    ["Jeong Woo-yeong", "FW", "Stuttgart", "GER"],
    ["Yang Hyun-jun", "FW", "Celtic", "SCO"],
    ["Kim Jin-su", "DF", "Jeonbuk", "KOR"],
    ["Lee Jae-sung", "MF", "Mainz", "GER"],
    ["Moon Seon-min", "FW", "Jeonbuk", "KOR"],
  ],
  CZE: [
    ["Tomáš Vaclík", "GK", "Basel", "SUI"],
    ["Jiří Pavlenka", "GK", "Union Berlin", "GER"],
    ["Vladimír Coufal", "DF", "West Ham", "ENG"],
    ["David Hovorka", "DF", "Slavia Prague", "CZE"],
    ["Ondřej Kúdela", "DF", "Slavia Prague", "CZE"],
    ["Tomáš Souček", "MF", "West Ham", "ENG"],
    ["Antonín Barák", "MF", "Fiorentina", "ITA"],
    ["Alex Král", "MF", "Union Berlin", "GER"],
    ["Lukáš Provod", "MF", "Slavia Prague", "CZE"],
    ["Michal Sadílek", "MF", "Twente", "NED"],
    ["Patrik Schick", "FW", "Bayer Leverkusen", "GER"],
    ["Jan Kuchta", "FW", "Sparta Prague", "CZE"],
    ["Adam Hložek", "FW", "Bayer Leverkusen", "GER"],
    ["Václav Jurečka", "FW", "Slavia Prague", "CZE"],
    ["Tomáš Chorý", "FW", "Slavia Prague", "CZE"],
    ["David Doudera", "DF", "Slavia Prague", "CZE"],
    ["Jaroslav Zelený", "DF", "Slavia Prague", "CZE"],
    ["Lukáš Cerv", "MF", "Viktoria Plzeň", "CZE"],
  ],
  CAN: [
    ["Milan Borjan", "GK", "Red Star Belgrade", "SRB"],
    ["Maxime Crépeau", "GK", "Portland Timbers", "USA"],
    ["Alphonso Davies", "DF", "Bayern Munich", "GER"],
    ["Sam Adekugbe", "DF", "Hatayspor", "TUR"],
    ["Derek Cornelius", "DF", "Marseille", "FRA"],
    ["Richie Laryea", "DF", "Toronto FC", "CAN"],
    ["Samuel Piette", "MF", "CF Montréal", "CAN"],
    ["Stephen Eustáquio", "MF", "Porto", "POR"],
    ["Jonathan Osorio", "MF", "Toronto FC", "CAN"],
    ["Atiba Hutchinson", "MF", "İstanbul Başakşehir", "TUR"],
    ["Alphonso Davies", "MF", "Bayern Munich", "GER"],
    ["Jonathan David", "FW", "Lille", "FRA"],
    ["Cyle Larin", "FW", "Mallorca", "ESP"],
    ["Liam Millar", "FW", "Preston North End", "ENG"],
    ["Tajon Buchanan", "FW", "Inter Milan", "ITA"],
    ["Jacob Shaffelburg", "FW", "Nashville SC", "USA"],
    ["Lucas Cavallini", "FW", "Vancouver Whitecaps", "CAN"],
    ["Junior Hoilett", "FW", "Reading", "ENG"],
  ],
  BIH: [
    ["Ibrahim Sehic", "GK", "Konyaspor", "TUR"],
    ["Kenan Piric", "GK", "AEK Larnaca", "CYP"],
    ["Sead Kolašinac", "DF", "Marseille", "FRA"],
    ["Stjepan Lončar", "DF", "Rijeka", "CRO"],
    ["Adis Jahović", "DF", "Sarajevo", "BIH"],
    ["Miralem Pjanić", "MF", "Sharjah", "UAE"],
    ["Rade Krunić", "MF", "Genoa", "ITA"],
    ["Amir Hadžiahmetović", "MF", "Konyaspor", "TUR"],
    ["Edin Džeko", "FW", "Fenerbahçe", "TUR"],
    ["Ermedin Demirović", "FW", "Stuttgart", "GER"],
    ["Miroslav Stevanović", "FW", "Servette", "SUI"],
    ["Benjamin Tahirović", "FW", "Hoffenheim", "GER"],
    ["Elvis Sarić", "MF", "Lech Poznań", "POL"],
    ["Anel Ahmedhodžić", "DF", "Sheffield United", "ENG"],
    ["Dennis Hadžikadunić", "DF", "Rostov", "RUS"],
    ["Edin Višća", "FW", "Trabzonspor", "TUR"],
    ["Mario Kvesić", "MF", "Kayserispor", "TUR"],
    ["Admir Lulić", "MF", "Sarajevo", "BIH"],
  ],
  QAT: [
    ["Saad Al-Sheeb", "GK", "Al-Sadd", "QAT"],
    ["Mishal Barsham", "GK", "Al-Sadd", "QAT"],
    ["Abdelkarim Hassan", "DF", "Al-Sadd", "QAT"],
    ["Boualem Khoukhi", "DF", "Al-Sadd", "QAT"],
    ["Pedro Miguel", "DF", "Al-Sadd", "QAT"],
    ["Homam Ahmed", "DF", "Al-Gharafa", "QAT"],
    ["Assim Madibo", "MF", "Al-Wakrah", "QAT"],
    ["Hassan Al-Haydos", "MF", "Al-Sadd", "QAT"],
    ["Akram Afif", "FW", "Al-Sadd", "QAT"],
    ["Almoez Ali", "FW", "Al-Duhail", "QAT"],
    ["Mohammed Muntari", "FW", "Al-Duhail", "QAT"],
    ["Yusuf Abdurisag", "FW", "Al-Arabi", "QAT"],
    ["Karim Boudiaf", "MF", "Al-Duhail", "QAT"],
    ["Ahmed Alaaeldin", "FW", "Al-Gharafa", "QAT"],
    ["Mohammed Waad", "MF", "Al-Sadd", "QAT"],
    ["Tarek Salman", "DF", "Al-Sadd", "QAT"],
    ["Bassam Al-Rawi", "DF", "Al-Rayyan", "QAT"],
    ["Ahmed Fadl", "MF", "Al-Arabi", "QAT"],
  ],
  SUI: [
    ["Yann Sommer", "GK", "Inter Milan", "ITA"],
    ["Gregor Kobel", "GK", "Borussia Dortmund", "GER"],
    ["Manuel Akanji", "DF", "Manchester City", "ENG"],
    ["Ricardo Rodríguez", "DF", "Torino", "ITA"],
    ["Fabian Schär", "DF", "Newcastle United", "ENG"],
    ["Silvan Widmer", "DF", "Mainz", "GER"],
    ["Granit Xhaka", "MF", "Bayer Leverkusen", "GER"],
    ["Remo Freuler", "MF", "Bologna", "ITA"],
    ["Ruben Vargas", "MF", "Augsburg", "GER"],
    ["Xherdan Shaqiri", "MF", "Chicago Fire", "USA"],
    ["Breel Embolo", "FW", "Monaco", "FRA"],
    ["Noah Okafor", "FW", "Milan", "ITA"],
    ["Dan Ndoye", "FW", "Bologna", "ITA"],
    ["Zeki Amdouni", "FW", "Burnley", "ENG"],
    ["Michel Aebischer", "MF", "Bologna", "ITA"],
    ["Denis Zakaria", "MF", "Monaco", "FRA"],
    ["Vincent Sierro", "MF", "Toulouse", "FRA"],
    ["Nico Elvedi", "DF", "Borussia Mönchengladbach", "GER"],
  ],
  BRA: [
    ["Alisson", "GK", "Liverpool", "ENG"],
    ["Ederson", "GK", "Manchester City", "ENG"],
    ["Marquinhos", "DF", "Paris Saint-Germain", "FRA"],
    ["Gabriel Magalhães", "DF", "Arsenal", "ENG"],
    ["Danilo", "DF", "Juventus", "ITA"],
    ["Wendell", "DF", "Porto", "POR"],
    ["Casemiro", "MF", "Manchester United", "ENG"],
    ["Bruno Guimarães", "MF", "Newcastle United", "ENG"],
    ["Paquetá", "MF", "West Ham", "ENG"],
    ["Rodrygo", "FW", "Real Madrid", "ESP"],
    ["Vinícius Júnior", "FW", "Real Madrid", "ESP"],
    ["Richarlison", "FW", "Tottenham", "ENG"],
    ["Endrick", "FW", "Real Madrid", "ESP"],
    ["Raphinha", "FW", "Barcelona", "ESP"],
    ["Gabriel Martinelli", "FW", "Arsenal", "ENG"],
    ["André", "MF", "Wolverhampton", "ENG"],
    ["Estêvão", "FW", "Palmeiras", "BRA"],
    ["Lucas Paquetá", "MF", "West Ham", "ENG"],
  ],
  MAR: [
    ["Yassine Bono", "GK", "Al-Hilal", "KSA"],
    ["Munir El Kajoui", "GK", "Wydad AC", "MAR"],
    ["Achraf Hakimi", "DF", "Paris Saint-Germain", "FRA"],
    ["Romain Saïss", "DF", "Al-Shabab", "KSA"],
    ["Nayef Aguerd", "DF", "Real Sociedad", "ESP"],
    ["Noussair Mazraoui", "DF", "Manchester United", "ENG"],
    ["Sofyan Amrabat", "MF", "Manchester United", "ENG"],
    ["Azzedine Ounahi", "MF", "Marseille", "FRA"],
    ["Selim Amallah", "MF", "Valencia", "ESP"],
    ["Hakim Ziyech", "MF", "Galatasaray", "TUR"],
    ["Youssef En-Nesyri", "FW", "Sevilla", "ESP"],
    ["Brahim Díaz", "FW", "Real Madrid", "ESP"],
    ["Sofiane Boufal", "FW", "Angers", "FRA"],
    ["Abde Ezzalzouli", "FW", "Real Betis", "ESP"],
    ["Amine Harit", "MF", "Marseille", "FRA"],
    ["Ayoub El Kaabi", "FW", "Olympiacos", "GRE"],
    ["Ismaël Saibari", "MF", "PSV", "NED"],
    ["Oussama Targhalline", "MF", "Feyenoord", "NED"],
  ],
  HAI: [
    ["Johny Placide", "GK", "Antwerp", "BEL"],
    ["Josue Duverger", "GK", "Violette AC", "HAI"],
    ["Derrick Etienne", "DF", "Los Angeles FC", "USA"],
    ["Carlens Arcus", "DF", "Auxerre", "FRA"],
    ["Mechack Joseph", "DF", "Lens", "FRA"],
    ["Zachary Herivaux", "MF", "Colorado Rapids", "USA"],
    ["Derrick Etienne Jr.", "MF", "Montreal", "CAN"],
    ["Bryan Alceus", "MF", "Gaziantep", "TUR"],
    ["Frantzdy Pierrot", "FW", "Salernitana", "ITA"],
    ["Duckens Nazon", "FW", "Saint-Étienne", "FRA"],
    ["Mondy Prunier", "FW", "Grenoble", "FRA"],
    ["Carnejy Antoine", "FW", "Portland Timbers", "USA"],
    ["Widner Saintcyr", "MF", "Violette AC", "HAI"],
    ["Bryan Labady", "FW", "Miami FC", "USA"],
    ["Danley Jean Jacques", "MF", "Le Havre", "FRA"],
    ["Ricardo Adé", "DF", "Miami FC", "USA"],
    ["Johannese Michel", "MF", "Violette AC", "HAI"],
    ["Wesley Lautoa", "DF", "Caen", "FRA"],
  ],
  SCO: [
    ["Angus Gunn", "GK", "Nottingham Forest", "ENG"],
    ["Craig Gordon", "GK", "Hearts", "SCO"],
    ["Kieran Tierney", "DF", "Real Sociedad", "ESP"],
    ["Grant Hanley", "DF", "Bristol City", "ENG"],
    ["Jack Hendry", "DF", "Al-Ettifaq", "KSA"],
    ["Andrew Robertson", "DF", "Liverpool", "ENG"],
    ["Scott McTominay", "MF", "Napoli", "ITA"],
    ["John McGinn", "MF", "Aston Villa", "ENG"],
    ["Ryan Christie", "MF", "Bournemouth", "ENG"],
    ["Billy Gilmour", "MF", "Napoli", "ITA"],
    ["Che Adams", "FW", "Torino", "ITA"],
    ["Lyndon Dykes", "FW", "QPR", "ENG"],
    ["Lawrence Shankland", "FW", "Club Brugge", "BEL"],
    ["Lewis Morgan", "FW", "New York Red Bulls", "USA"],
    ["Kenny McLean", "MF", "Norwich City", "ENG"],
    ["Callum McGregor", "MF", "Celtic", "SCO"],
    ["Anthony Ralston", "DF", "Celtic", "SCO"],
    ["Lewis Ferguson", "MF", "Bologna", "ITA"],
  ],
  USA: [
    ["Matt Turner", "GK", "Nottingham Forest", "ENG"],
    ["Ethan Horvath", "GK", "Cardiff City", "WAL"],
    ["Chris Richards", "DF", "Crystal Palace", "ENG"],
    ["Antonee Robinson", "DF", "Fulham", "ENG"],
    ["Walker Zimmerman", "DF", "Dallas", "USA"],
    ["Sergiño Dest", "DF", "PSV", "NED"],
    ["Tyler Adams", "MF", "Bournemouth", "ENG"],
    ["Weston McKennie", "MF", "Juventus", "ITA"],
    ["Yunus Musah", "MF", "Milan", "ITA"],
    ["Gio Reyna", "MF", "Borussia Dortmund", "GER"],
    ["Christian Pulisic", "FW", "Milan", "ITA"],
    ["Folarin Balogun", "FW", "Monaco", "FRA"],
    ["Ricardo Pepi", "FW", "PSV", "NED"],
    ["Haji Wright", "FW", "Coventry City", "ENG"],
    ["Tim Weah", "FW", "Juventus", "ITA"],
    ["Brenden Aaronson", "MF", "Union Berlin", "GER"],
    ["Johnny Cardoso", "MF", "Real Betis", "ESP"],
    ["Malik Tillman", "MF", "Bayer Leverkusen", "GER"],
  ],
  PAR: [
    ["Antony Silva", "GK", "Olimpia", "PAR"],
    ["Gerardo Ortiz", "GK", "Libertad", "PAR"],
    ["Gustavo Gómez", "DF", "Palmeiras", "BRA"],
    ["Omar Alderete", "DF", "Getafe", "ESP"],
    ["Blas Riveros", "DF", "Braga", "POR"],
    ["Matías Rojas", "MF", "Inter Miami", "USA"],
    ["Miguel Almirón", "MF", "Newcastle United", "ENG"],
    ["Richard Sánchez", "MF", "América", "MEX"],
    ["Diego Gómez", "MF", "Inter Miami", "USA"],
    ["Julio Enciso", "FW", "Brighton", "ENG"],
    ["Antonio Sanabria", "FW", "Torino", "ITA"],
    ["Gabriel Avalos", "FW", "Argentinos Juniors", "ARG"],
    ["Carlos González", "FW", "Olimpia", "PAR"],
    ["Alejandro Romero Gamarra", "FW", "Al-Rayyan", "QAT"],
    ["Ramón Sosa", "FW", "Nottingham Forest", "ENG"],
    ["Juan Iturbe", "FW", "Guaraní", "PAR"],
    ["Héctor Morel", "DF", "Libertad", "PAR"],
    ["Júnior Alonso", "DF", "Krasnodar", "RUS"],
  ],
  AUS: [
    ["Mathew Ryan", "GK", "Roma", "ITA"],
    ["Mark Gillespie", "GK", "Newcastle Jets", "AUS"],
    ["Harry Souttar", "DF", "Sheffield United", "ENG"],
    ["Kye Rowles", "DF", "Hearts", "SCO"],
    ["Aziz Behich", "DF", "Melbourne City", "AUS"],
    ["Jackson Irvine", "MF", "St. Pauli", "GER"],
    ["Riley McGree", "MF", "Middlesbrough", "ENG"],
    ["Aiden O'Neill", "MF", "Millwall", "ENG"],
    ["Craig Goodwin", "MF", "Adelaide United", "AUS"],
    ["Mathew Leckie", "FW", "Melbourne City", "AUS"],
    ["Mitchell Duke", "FW", "Machida Zelvia", "JPN"],
    ["Martin Boyle", "FW", "Hibernian", "SCO"],
    ["Brandon Borrello", "FW", "Western Sydney", "AUS"],
    ["Garang Kuol", "FW", "Volendam", "NED"],
    ["Nestory Irankunda", "FW", "Watford", "ENG"],
    ["Keanu Baccus", "MF", "St. Mirren", "SCO"],
    ["Connor Metcalfe", "MF", "Hamburger SV", "GER"],
    ["Bailey Wright", "DF", "Coventry City", "ENG"],
  ],
  TUR: [
    ["Uğurcan Çakır", "GK", "Trabzonspor", "TUR"],
    ["Altay Bayındır", "GK", "Manchester United", "ENG"],
    ["Merih Demiral", "DF", "Al-Ahli", "KSA"],
    ["Çağlar Söyüncü", "DF", "Fenerbahçe", "TUR"],
    ["Zeki Çelik", "DF", "Roma", "ITA"],
    ["Hakan Çalhanoğlu", "MF", "Inter Milan", "ITA"],
    ["Orkun Kökçü", "MF", "Benfica", "POR"],
    ["İrfan Can Kahveci", "MF", "Fenerbahçe", "TUR"],
    ["Arda Güler", "MF", "Real Madrid", "ESP"],
    ["Kenan Yıldız", "FW", "Juventus", "ITA"],
    ["Cenk Tosun", "FW", "Beşiktaş", "TUR"],
    ["Barış Alper Yılmaz", "FW", "Galatasaray", "TUR"],
    ["Enes Ünal", "FW", "Getafe", "ESP"],
    ["Kerem Aktürkoğlu", "FW", "Benfica", "POR"],
    ["Yunus Akgün", "FW", "Galatasaray", "TUR"],
    ["Salih Özcan", "MF", "Borussia Dortmund", "GER"],
    ["Ferdi Kadıoğlu", "DF", "Brighton", "ENG"],
    ["Abdülkerim Bardakcı", "DF", "Galatasaray", "TUR"],
  ],
  GER: [
    ["Manuel Neuer", "GK", "Bayern Munich", "GER"],
    ["Marc-André ter Stegen", "GK", "Barcelona", "ESP"],
    ["Antonio Rüdiger", "DF", "Real Madrid", "ESP"],
    ["Jonathan Tah", "DF", "Bayer Leverkusen", "GER"],
    ["David Raum", "DF", "RB Leipzig", "GER"],
    ["Joshua Kimmich", "MF", "Bayern Munich", "GER"],
    ["İlkay Gündoğan", "MF", "Manchester City", "ENG"],
    ["Florian Wirtz", "MF", "Bayer Leverkusen", "GER"],
    ["Jamal Musiala", "MF", "Bayern Munich", "GER"],
    ["Kai Havertz", "FW", "Arsenal", "ENG"],
    ["Niclas Füllkrug", "FW", "West Ham", "ENG"],
    ["Leroy Sané", "FW", "Bayern Munich", "GER"],
    ["Serge Gnabry", "FW", "Bayern Munich", "GER"],
    ["Timo Werner", "FW", "Tottenham", "ENG"],
    ["Niclas Fullkrug", "FW", "West Ham", "ENG"],
    ["Felix Nmecha", "MF", "Borussia Dortmund", "GER"],
    ["Maximilian Mittelstädt", "DF", "Stuttgart", "GER"],
    ["Robin Gosens", "DF", "Fiorentina", "ITA"],
  ],
  CUW: [
    ["Eloy Room", "GK", "PSV", "NED"],
    ["Jurich Brown", "GK", "Vitesse", "NED"],
    ["Sherel Floranus", "DF", "Almere City", "NED"],
    ["Juriën Gaari", "DF", "Al-Batin", "KSA"],
    ["Brandley Kuwas", "MF", "Groningen", "NED"],
    ["Leandro Bacuna", "MF", "Cardiff City", "WAL"],
    ["Roly Bonevacia", "MF", "Al-Jazira", "UAE"],
    ["Crysencio Summerville", "FW", "West Ham", "ENG"],
    ["Elson Hooi", "FW", "Cambuur", "NED"],
    ["Gervane Kastaneer", "FW", "Twente", "NED"],
    ["Jarchinio Antonia", "FW", "Volendam", "NED"],
    ["Rangelo Janga", "FW", "Astana", "KAZ"],
    ["Juriën Gaari", "DF", "Al-Batin", "KSA"],
    ["Shanon Carmelia", "FW", "Helmond Sport", "NED"],
    ["Brandley Martis", "DF", "Sparta Rotterdam", "NED"],
    ["Juriën Gaari", "MF", "Al-Batin", "KSA"],
    ["Gino van Kessel", "FW", "TOP Oss", "NED"],
    ["Juriën Gaari", "FW", "Al-Batin", "KSA"],
  ],
  CIV: [
    ["Badra Ali Sangaré", "GK", "Pyramids", "EGY"],
    ["Yahia Fofana", "GK", "Angers", "FRA"],
    ["Serge Aurier", "DF", "Villarreal", "ESP"],
    ["Ousmane Diomande", "DF", "Sporting CP", "POR"],
    ["Wilfried Singo", "DF", "Monaco", "FRA"],
    ["Franck Kessié", "MF", "Al-Ahli", "KSA"],
    ["Jean-Philippe Krasso", "FW", "Sunderland", "ENG"],
    ["Sébastien Haller", "FW", "Borussia Dortmund", "GER"],
    ["Nicolas Pépé", "FW", "Villarreal", "ESP"],
    ["Simon Adingra", "FW", "Brighton", "ENG"],
    ["Jérémie Boga", "FW", "Nice", "FRA"],
    ["Ibrahim Sangaré", "MF", "Nottingham Forest", "ENG"],
    ["Habib Maiga", "MF", "Troyes", "FRA"],
    ["Max-Alain Gradel", "FW", "Sivasspor", "TUR"],
    ["Amad Diallo", "FW", "Manchester United", "ENG"],
    ["Christian Kouakou", "MF", "Basel", "SUI"],
    ["Odilon Kossounou", "DF", "Atalanta", "ITA"],
    ["Ghislain Konan", "DF", "Al-Fayha", "KSA"],
  ],
  ECU: [
    ["Alexander Domínguez", "GK", "LDU Quito", "ECU"],
    ["Hernán Galíndez", "GK", "Aucas", "ECU"],
    ["Piero Hincapié", "DF", "Bayer Leverkusen", "GER"],
    ["Felix Torres", "DF", "Santos Laguna", "MEX"],
    ["Angelo Preciado", "DF", "Genk", "BEL"],
    ["Moisés Caicedo", "MF", "Chelsea", "ENG"],
    ["Carlos Gruezo", "MF", "San Jose Earthquakes", "USA"],
    ["Kendry Páez", "MF", "Independiente del Valle", "ECU"],
    ["Enner Valencia", "FW", "Internacional", "BRA"],
    ["Jeremy Sarmiento", "FW", "Brighton", "ENG"],
    ["Pervis Estupiñán", "DF", "Brighton", "ENG"],
    ["Willian Pacho", "DF", "Paris Saint-Germain", "FRA"],
    ["Michael Estrada", "FW", "Cruz Azul", "MEX"],
    ["Jordy Caicedo", "FW", "Independiente del Valle", "ECU"],
    ["Kevin Rodriguez", "FW", "Union Saint-Gilloise", "BEL"],
    ["Alan Franco", "MF", "Atlético Mineiro", "BRA"],
    ["José Cifuentes", "MF", "Los Angeles FC", "USA"],
    ["Gonzalo Plata", "FW", "Flamengo", "BRA"],
  ],
  NED: [
    ["Virgil van Dijk", "DF", "Liverpool", "ENG"],
    ["Nathan Aké", "DF", "Manchester City", "ENG"],
    ["Denzel Dumfries", "DF", "Inter Milan", "ITA"],
    ["Jurriën Timber", "DF", "Arsenal", "ENG"],
    ["Frenkie de Jong", "MF", "Barcelona", "ESP"],
    ["Tijjani Reijnders", "MF", "Milan", "ITA"],
    ["Ryan Gravenberch", "MF", "Liverpool", "ENG"],
    ["Steven Bergwijn", "FW", "Al-Ittihad", "KSA"],
    ["Memphis Depay", "FW", "Corinthians", "BRA"],
    ["Cody Gakpo", "FW", "Liverpool", "ENG"],
    ["Brian Brobbey", "FW", "Ajax", "NED"],
    ["Wout Weghorst", "FW", "Ajax", "NED"],
    ["Xavi Simons", "MF", "RB Leipzig", "GER"],
    ["Donyell Malen", "FW", "Aston Villa", "ENG"],
    ["Jeremie Frimpong", "DF", "Bayer Leverkusen", "GER"],
    ["Mark Flekken", "GK", "Brentford", "ENG"],
    ["Bart Verbruggen", "GK", "Brighton", "ENG"],
    ["Ian Maatsen", "DF", "Aston Villa", "ENG"],
  ],
  JPN: [
    ["Gonda Shuichi", "GK", "Shimizu S-Pulse", "JPN"],
    ["Suzuki Zion", "GK", "Parma", "ITA"],
    ["Itakura Ko", "DF", "Manchester City", "ENG"],
    ["Tomiyasu Takehiro", "DF", "Arsenal", "ENG"],
    ["Taniguchi Ko", "DF", "Reims", "FRA"],
    ["Endo Wataru", "MF", "Liverpool", "ENG"],
    ["Kamada Daichi", "MF", "Lazio", "ITA"],
    ["Minamino Takumi", "MF", "Monaco", "FRA"],
    ["Kubo Takefusa", "FW", "Real Sociedad", "ESP"],
    ["Mitoma Kaoru", "FW", "Brighton", "ENG"],
    ["Asano Takuma", "FW", "Mainz", "GER"],
    ["Doan Ritsu", "FW", "Freiburg", "GER"],
    ["Soma Yuki", "FW", "Cerezo Osaka", "JPN"],
    ["Ueda Ayase", "FW", "Feyenoord", "NED"],
    ["Ito Junya", "FW", "Reims", "FRA"],
    ["Suzuki Yuito", "FW", "Brugge", "BEL"],
    ["Morita Hidemasa", "MF", "Sporting CP", "POR"],
    ["Tanaka Ao", "MF", "Fortuna Düsseldorf", "GER"],
  ],
  SWE: [
    ["Robin Olsen", "GK", "Malmö FF", "SWE"],
    ["Kristoffer Kjölan", "GK", "Hammarby", "SWE"],
    ["Victor Lindelöf", "DF", "Manchester United", "ENG"],
    ["Isak Hien", "DF", "Atalanta", "ITA"],
    ["Ludwig Augustinsson", "DF", "Malmö FF", "SWE"],
    ["Emil Forsberg", "MF", "New York Red Bulls", "USA"],
    ["Dejan Kulusevski", "MF", "Tottenham", "ENG"],
    ["Mattias Svanberg", "MF", "Wolfsburg", "GER"],
    ["Alexander Isak", "FW", "Newcastle United", "ENG"],
    ["Viktor Gyökeres", "FW", "Sporting CP", "POR"],
    ["Anthony Elanga", "FW", "Nottingham Forest", "ENG"],
    ["Jesper Karlsson", "FW", "Bologna", "ITA"],
    ["Aron El Kadiri", "FW", "Malmo FF", "SWE"],
    ["Gustav Berggren", "MF", "Rosenborg", "NOR"],
    ["Jesper Ceesay", "DF", "AIK", "SWE"],
    ["Hugo Larsson", "MF", "Eintracht Frankfurt", "GER"],
    ["Simon Olsson", "MF", "Heerenveen", "NED"],
    ["Willem Gevers", "DF", "Hammarby", "SWE"],
  ],
  TUN: [
    ["Aymen Dahmen", "GK", "Club Africain", "TUN"],
    ["Mouez Hassen", "GK", "Club Africain", "TUN"],
    ["Yassine Meriah", "DF", "Espérance", "TUN"],
    ["Montassar Talbi", "DF", "Lorient", "FRA"],
    ["Ali Maaloul", "DF", "Al-Ahly", "EGY"],
    ["Ellyes Skhiri", "MF", "Eintracht Frankfurt", "GER"],
    ["Aïssa Laïdouni", "MF", "Union Berlin", "GER"],
    ["Hamza Rafia", "MF", "Lecce", "ITA"],
    ["Wahbi Khazri", "FW", "Montpellier", "FRA"],
    ["Issam Jebali", "FW", "IF Elfsborg", "SWE"],
    ["Taha Yassine Khenissi", "FW", "Espérance", "TUN"],
    ["Seifeddine Jaziri", "FW", "Zamalek", "EGY"],
    ["Naim Sliti", "FW", "Al-Ettifaq", "KSA"],
    ["Hamza Lahmar", "MF", "Espérance", "TUN"],
    ["Anis Ben Slimane", "MF", "Sheffield United", "ENG"],
    ["Youssef Msakni", "FW", "Al-Arabi", "QAT"],
    ["Oussama Khazri", "FW", "Montpellier", "FRA"],
    ["Bilel Ifa", "DF", "Kuwait SC", "KUW"],
  ],
  BEL: [
    ["Thibaut Courtois", "GK", "Real Madrid", "ESP"],
    ["Koen Casteels", "GK", "Wolfsburg", "GER"],
    ["Timothy Castagne", "DF", "Fulham", "ENG"],
    ["Arthur Theate", "DF", "Eintracht Frankfurt", "GER"],
    ["Zeno Debast", "DF", "Sporting CP", "POR"],
    ["Kevin De Bruyne", "MF", "Manchester City", "ENG"],
    ["Youri Tielemans", "MF", "Aston Villa", "ENG"],
    ["Amadou Onana", "MF", "Everton", "ENG"],
    ["Romelu Lukaku", "FW", "Napoli", "ITA"],
    ["Loïs Openda", "FW", "RB Leipzig", "GER"],
    ["Dodi Lukebakio", "FW", "Sevilla", "ESP"],
    ["Charles De Ketelaere", "FW", "Atalanta", "ITA"],
    ["Jérémy Doku", "FW", "Manchester City", "ENG"],
    ["Leandro Trossard", "FW", "Arsenal", "ENG"],
    ["Johan Bakayoko", "FW", "PSV", "NED"],
    ["Axel Witsel", "MF", "Atlético Madrid", "ESP"],
    ["Thomas Meunier", "DF", "Trabzonspor", "TUR"],
    ["Orel Mangala", "MF", "Lyon", "FRA"],
  ],
  EGY: [
    ["Mohamed El Shenawy", "GK", "Al-Ahly", "EGY"],
    ["Mohamed Abou Gabal", "GK", "Zamalek", "EGY"],
    ["Ahmed Hegazi", "DF", "Al-Ittihad", "KSA"],
    ["Mohamed Hany", "DF", "Al-Ahly", "EGY"],
    ["Mohamed Abdelmonem", "DF", "Nice", "FRA"],
    ["Mohamed Elneny", "MF", "Arsenal", "ENG"],
    ["Emam Ashour", "MF", "Al-Ahly", "EGY"],
    ["Mohamed Salah", "FW", "Liverpool", "ENG"],
    ["Omar Marmoush", "FW", "Eintracht Frankfurt", "GER"],
    ["Mostafa Mohamed", "FW", "Nantes", "FRA"],
    ["Ahmed Hassan", "FW", "Panathinaikos", "GRE"],
    ["Trézéguet", "FW", "Al-Ahly", "EGY"],
    ["Marwan Hamdy", "FW", "Al-Ettifaq", "KSA"],
    ["Zizo", "FW", "Al-Ahly", "EGY"],
    ["Mohamed Magdy", "MF", "Pyramids", "EGY"],
    ["Mahmoud Trezeguet", "FW", "Al-Ahly", "EGY"],
    ["Ahmed Sayed Zizo", "FW", "Al-Ahly", "EGY"],
    ["Mohamed Abdelrazek", "DF", "Zamalek", "EGY"],
  ],
  IRN: [
    ["Alireza Beiranvand", "GK", "Persepolis", "IRN"],
    ["Hossein Hosseini", "GK", "Esteghlal", "IRN"],
    ["Ramin Rezaeian", "DF", "Al-Shabab", "KSA"],
    ["Shojae Khalilzadeh", "DF", "Tractor", "IRN"],
    ["Milad Mohammadi", "DF", "AEK Athens", "GRE"],
    ["Saeid Ezatolahi", "MF", "Rostov", "RUS"],
    ["Alireza Jahanbakhsh", "FW", "Feyenoord", "NED"],
    ["Sardar Azmoun", "FW", "Shabab Al-Ahli", "UAE"],
    ["Mehdi Taremi", "FW", "Inter Milan", "ITA"],
    ["Saman Ghoddos", "FW", "Brentford", "ENG"],
    ["Karim Ansarifard", "FW", "AEK Athens", "GRE"],
    ["Vahid Amiri", "MF", "Persepolis", "IRN"],
    ["Omid Noorafkan", "MF", "Sepahan", "IRN"],
    ["Rouzbeh Cheshmi", "DF", "Esteghlal", "IRN"],
    ["Hossein Kanani", "DF", "Persepolis", "IRN"],
    ["Mohammad Mohebi", "FW", "Rostov", "RUS"],
    ["Mehdi Ghayedi", "FW", "Ajman", "UAE"],
    ["Abolfazl Jalali", "DF", "Esteghlal", "IRN"],
  ],
  NZL: [
    ["Oliver Sail", "GK", "Wellington Phoenix", "NZL"],
    ["Michael Boxall", "DF", "Minnesota United", "USA"],
    ["Bill Tuiloma", "DF", "Portland Timbers", "USA"],
    ["Nando Pijker", "DF", "Heerenveen", "NED"],
    ["Marko Stamenić", "MF", "Nottingham Forest", "ENG"],
    ["Clayton Lewis", "MF", "Western Sydney", "AUS"],
    ["Marco Rojas", "MF", "Melbourne Victory", "AUS"],
    ["Chris Wood", "FW", "Nottingham Forest", "ENG"],
    ["Ben Waine", "FW", "Wellington Phoenix", "NZL"],
    ["Elijah Just", "FW", "HJK", "FIN"],
    ["Alex Greive", "FW", "Bristol Rovers", "ENG"],
    ["Marco van Ginkel", "MF", "PSV", "NED"],
    ["Finn Surman", "DF", "Wellington Phoenix", "NZL"],
    ["Dane Ingham", "DF", "New York Red Bulls", "USA"],
    ["Callum McCowatt", "MF", "Motherwell", "SCO"],
    ["Ben Old", "FW", "Real Salt Lake", "USA"],
    ["Justín Gulley", "MF", "Wellington Phoenix", "NZL"],
    ["Kosta Barbarouses", "FW", "Sydney FC", "AUS"],
  ],
  ESP: [
    ["Unai Simón", "GK", "Athletic Club", "ESP"],
    ["David Raya", "GK", "Arsenal", "ENG"],
    ["Aymeric Laporte", "DF", "Al-Nassr", "KSA"],
    ["Robin Le Normand", "DF", "Atlético Madrid", "ESP"],
    ["Jordi Alba", "DF", "Miami", "USA"],
    ["Rodri", "MF", "Manchester City", "ENG"],
    ["Pedri", "MF", "Barcelona", "ESP"],
    ["Gavi", "MF", "Barcelona", "ESP"],
    ["Fabián Ruiz", "MF", "Paris Saint-Germain", "FRA"],
    ["Álvaro Morata", "FW", "Milan", "ITA"],
    ["Dani Olmo", "FW", "Barcelona", "ESP"],
    ["Nico Williams", "FW", "Athletic Club", "ESP"],
    ["Lamine Yamal", "FW", "Barcelona", "ESP"],
    ["Ferran Torres", "FW", "Barcelona", "ESP"],
    ["Mikel Oyarzabal", "FW", "Real Sociedad", "ESP"],
    ["Joselu", "FW", "Al-Gharafa", "QAT"],
    ["Marco Asensio", "FW", "Paris Saint-Germain", "FRA"],
    ["Alejandro Baena", "MF", "Villarreal", "ESP"],
  ],
  CPV: [
    ["Vozinha", "GK", "AEL Limassol", "CYP"],
    ["Marco", "GK", "Casa Pia", "POR"],
    ["Stopira", "DF", "Feirense", "POR"],
    ["Jójó", "DF", "Famalicão", "POR"],
    ["Dylan Tavares", "FW", "Basel", "SUI"],
    ["Ryan Mendes", "FW", "Al-Nasr", "UAE"],
    ["Jovane Cabral", "FW", "Sparta Prague", "CZE"],
    ["Garry Rodrigues", "FW", "Al-Ittihad", "KSA"],
    ["Bébé", "FW", "Rayo Vallecano", "ESP"],
    ["Patrick Andrade", "MF", "Qadsia", "KUW"],
    ["Platini", "FW", "Santa Clara", "POR"],
    ["Willy Semedo", "FW", "Göztepe", "TUR"],
    ["Kevyn", "MF", "Famalicão", "POR"],
    ["Diney", "DF", "Moreirense", "POR"],
    ["Geovani", "MF", "Santa Clara", "POR"],
    ["Jerson", "FW", "Moreirense", "POR"],
    ["Kenny Rocha Santos", "MF", "Famalicão", "POR"],
    ["Bruno Leite", "DF", "Moreirense", "POR"],
  ],
  KSA: [
    ["Mohammed Al-Owais", "GK", "Al-Hilal", "KSA"],
    ["Yassine Bono", "GK", "Al-Hilal", "KSA"],
    ["Sultan Al-Ghannam", "DF", "Al-Nassr", "KSA"],
    ["Ali Al-Bulaihi", "DF", "Al-Hilal", "KSA"],
    ["Yasser Al-Shahrani", "DF", "Al-Hilal", "KSA"],
    ["Salem Al-Dawsari", "MF", "Al-Hilal", "KSA"],
    ["Salman Al-Faraj", "MF", "Al-Hilal", "KSA"],
    ["Saud Abdulhamid", "DF", "Roma", "ITA"],
    ["Firas Al-Buraikan", "FW", "Al-Shabab", "KSA"],
    ["Saleh Al-Shehri", "FW", "Al-Hilal", "KSA"],
    ["Abdullah Al-Hamdan", "FW", "Al-Hilal", "KSA"],
    ["Fahad Al-Muwallad", "FW", "Al-Ittihad", "KSA"],
    ["Musab Al-Juwair", "MF", "Al-Hilal", "KSA"],
    ["Nasser Al-Dawsari", "MF", "Al-Nassr", "KSA"],
    ["Abdulellah Al-Malki", "MF", "Al-Shabab", "KSA"],
    ["Mohammed Al-Breik", "DF", "Al-Hilal", "KSA"],
    ["Hassan Al-Tambakti", "DF", "Al-Shabab", "KSA"],
    ["Sami Al-Najei", "MF", "Al-Nassr", "KSA"],
  ],
  URY: [
    ["Sergio Rochet", "GK", "Nacional", "URY"],
    ["Fernando Muslera", "GK", "Peñarol", "URY"],
    ["José María Giménez", "DF", "Atlético Madrid", "ESP"],
    ["Ronald Araújo", "DF", "Barcelona", "ESP"],
    ["Guillermo Varela", "DF", "Flamengo", "BRA"],
    ["Federico Valverde", "MF", "Real Madrid", "ESP"],
    ["Rodrigo Bentancur", "MF", "Tottenham", "ENG"],
    ["Manuel Ugarte", "MF", "Manchester United", "ENG"],
    ["Darwin Núñez", "FW", "Liverpool", "ENG"],
    ["Luis Suárez", "FW", "Inter Miami", "USA"],
    ["Facundo Pellistri", "FW", "Manchester United", "ENG"],
    ["Giorgian Arrascaeta", "MF", "Flamengo", "BRA"],
    ["Maxi Gómez", "FW", "Trabzonspor", "TUR"],
    ["Facundo Torres", "FW", "Orlando City", "USA"],
    ["Agustín Canobbio", "FW", "Athletico Paranaense", "BRA"],
    ["Matías Viña", "DF", "Flamengo", "BRA"],
    ["Nahitan Nández", "MF", "Cagliari", "ITA"],
    ["Sebastián Coates", "DF", "Sporting CP", "POR"],
  ],
  FRA: [
    ["Mike Maignan", "GK", "Milan", "ITA"],
    ["Alphonse Areola", "GK", "West Ham", "ENG"],
    ["William Saliba", "DF", "Arsenal", "ENG"],
    ["Dayot Upamecano", "DF", "Bayern Munich", "GER"],
    ["Jules Koundé", "DF", "Barcelona", "ESP"],
    ["Aurélien Tchouaméni", "MF", "Real Madrid", "ESP"],
    ["Adrien Rabiot", "MF", "Milan", "ITA"],
    ["Warren Zaïre-Emery", "MF", "Paris Saint-Germain", "FRA"],
    ["Kylian Mbappé", "FW", "Real Madrid", "ESP"],
    ["Ousmane Dembélé", "FW", "Paris Saint-Germain", "FRA"],
    ["Olivier Giroud", "FW", "LA Galaxy", "USA"],
    ["Antoine Griezmann", "FW", "Atlético Madrid", "ESP"],
    ["Randal Kolo Muani", "FW", "Juventus", "ITA"],
    ["Bradley Barcola", "FW", "Paris Saint-Germain", "FRA"],
    ["Marcus Thuram", "FW", "Inter Milan", "ITA"],
    ["Kingsley Coman", "FW", "Bayern Munich", "GER"],
    ["Youssouf Fofana", "MF", "Milan", "ITA"],
    ["Ibrahima Konaté", "DF", "Liverpool", "ENG"],
  ],
  SEN: [
    ["Édouard Mendy", "GK", "Al-Ahli", "KSA"],
    ["Boubacar Diallo", "GK", "Metz", "FRA"],
    ["Kalidou Koulibaly", "DF", "Al-Hilal", "KSA"],
    ["Abdou Diallo", "DF", "Al-Arabi", "QAT"],
    ["Ismail Jakobs", "DF", "Monaco", "FRA"],
    ["Idrissa Gueye", "MF", "Everton", "ENG"],
    ["Pape Matar Sarr", "MF", "Tottenham", "ENG"],
    ["Sadio Mané", "FW", "Al-Nassr", "KSA"],
    ["Nicolas Jackson", "FW", "Chelsea", "ENG"],
    ["Boulaye Dia", "FW", "Lazio", "ITA"],
    ["El Bilal Touré", "FW", "VfB Stuttgart", "GER"],
    ["Iliman Ndiaye", "FW", "Everton", "ENG"],
    ["Formose Mendy", "DF", "Brest", "FRA"],
    ["Cheikh Kouyaté", "MF", "Nottingham Forest", "ENG"],
    ["Moussa Niakhaté", "DF", "Lyon", "FRA"],
    ["Lamine Camara", "MF", "Monaco", "FRA"],
    ["Habib Diallo", "FW", "Al-Shabab", "KSA"],
    ["Pape Gueye", "MF", "Marseille", "FRA"],
  ],
  IRQ: [
    ["Jalal Hassan", "GK", "Al-Shorta", "IRQ"],
    ["Ahmed Basim", "GK", "Al-Zawraa", "IRQ"],
    ["Ali Adnan", "DF", "Al-Shorta", "IRQ"],
    ["Saad Natiq", "DF", "Al-Shorta", "IRQ"],
    ["Manar Ismail", "DF", "Al-Zawraa", "IRQ"],
    ["Amjad Attwan", "MF", "Al-Shorta", "IRQ"],
    ["Zaid Mahdi", "MF", "Al-Zawraa", "IRQ"],
    ["Aymen Hussein", "FW", "Al-Shorta", "IRQ"],
    ["Mohanad Ali", "FW", "Al-Gharafa", "QAT"],
    ["Aso Rostam", "FW", "Al-Zawraa", "IRQ"],
    ["Bashar Resan", "MF", "Al-Gharafa", "QAT"],
    ["Ali Faez", "DF", "Al-Shorta", "IRQ"],
    ["Hussein Ali", "MF", "Al-Zawraa", "IRQ"],
    ["Ahmed Yasin", "FW", "Al-Shorta", "IRQ"],
    ["Rebin Sulaka", "DF", "Al-Zawraa", "IRQ"],
    ["Mustafa Saadoun", "MF", "Al-Shorta", "IRQ"],
    ["Ali Jasim", "FW", "Al-Shorta", "IRQ"],
    ["Hussein Saeed", "FW", "Al-Shorta", "IRQ"],
  ],
  NOR: [
    ["Bernd Leno", "GK", "Fulham", "ENG"],
    ["Ørjan Nyland", "GK", "Sevilla", "ESP"],
    ["Stefan Strandberg", "DF", "Rosenborg", "NOR"],
    ["Kristoffer Ajer", "DF", "Brentford", "ENG"],
    ["Felix Myhre", "MF", "Vålerenga", "NOR"],
    ["Martin Ødegaard", "MF", "Arsenal", "ENG"],
    ["Sander Berge", "MF", "Fulham", "ENG"],
    ["Patrick Berg", "MF", "Bodø/Glimt", "NOR"],
    ["Erling Haaland", "FW", "Manchester City", "ENG"],
    ["Alexander Sørloth", "FW", "Atlético Madrid", "ESP"],
    ["Joshua King", "FW", "Toulouse", "FRA"],
    ["Antoine Semenyo", "FW", "Bournemouth", "ENG"],
    ["Aron Dønnum", "MF", "Toulouse", "FRA"],
    ["Fredrik Aursnes", "MF", "Benfica", "POR"],
    ["Morten Thorsby", "MF", "Genoa", "ITA"],
    ["Julian Ryerson", "DF", "Borussia Dortmund", "GER"],
    ["Marcus Pedersen", "DF", "Torino", "ITA"],
    ["Leo Østigård", "DF", "Genoa", "ITA"],
  ],
  ARG: [
    ["Emiliano Martínez", "GK", "Aston Villa", "ENG"],
    ["Franco Armani", "GK", "River Plate", "ARG"],
    ["Cristian Romero", "DF", "Tottenham", "ENG"],
    ["Nicolás Otamendi", "DF", "Benfica", "POR"],
    ["Marcos Acuña", "DF", "River Plate", "ARG"],
    ["Rodrigo De Paul", "MF", "Atlético Madrid", "ESP"],
    ["Enzo Fernández", "MF", "Chelsea", "ENG"],
    ["Alexis Mac Allister", "MF", "Liverpool", "ENG"],
    ["Lionel Messi", "FW", "Inter Miami", "USA"],
    ["Lautaro Martínez", "FW", "Inter Milan", "ITA"],
    ["Julián Álvarez", "FW", "Atlético Madrid", "ESP"],
    ["Ángel Di María", "FW", "Benfica", "POR"],
    ["Giovani Lo Celso", "MF", "Real Betis", "ESP"],
    ["Nicolás González", "FW", "Juventus", "ITA"],
    ["Paulo Dybala", "FW", "Roma", "ITA"],
    ["Leandro Paredes", "MF", "Roma", "ITA"],
    ["Exequiel Palacios", "MF", "Bayer Leverkusen", "GER"],
    ["Germán Pezzella", "DF", "River Plate", "ARG"],
  ],
  ALG: [
    ["Raïs M'Bolhi", "GK", "CR Belouizdad", "ALG"],
    ["Anthony Mandrea", "GK", "Caen", "FRA"],
    ["Ramy Bensebaini", "DF", "Borussia Dortmund", "GER"],
    ["Aissa Mandi", "DF", "Villarreal", "ESP"],
    ["Youcef Atal", "DF", "Nice", "FRA"],
    ["Ismaël Bennacer", "MF", "Milan", "ITA"],
    ["Ramiz Zerrouki", "MF", "Twente", "NED"],
    ["Houssem Aouar", "MF", "Al-Ittihad", "KSA"],
    ["Riyad Mahrez", "FW", "Al-Ahli", "KSA"],
    ["Youcef Belaïli", "FW", "Qadsia", "KUW"],
    ["Baghdad Bounedjah", "FW", "Al-Rayyan", "QAT"],
    ["Islam Slimani", "FW", "Anderlecht", "BEL"],
    ["Mohamed Amoura", "FW", "Wolfsburg", "GER"],
    ["Rachid Ghezzal", "FW", "Al-Jazira", "UAE"],
    ["Adam Ounas", "FW", "Empoli", "ITA"],
    ["Amine Gouiri", "FW", "Rennes", "FRA"],
    ["Sofiane Feghouli", "MF", "AEK Athens", "GRE"],
    ["Zineddine Belaid", "DF", "USM Alger", "ALG"],
  ],
  AUT: [
    ["Daniel Bachmann", "GK", "Stoke City", "ENG"],
    ["Heinz Lindner", "GK", "WSG Tirol", "AUT"],
    ["David Alaba", "DF", "Real Madrid", "ESP"],
    ["Kevin Wimmer", "DF", "Glasgow Rangers", "SCO"],
    ["Philipp Lienhart", "DF", "Freiburg", "GER"],
    ["Marcel Sabitzer", "MF", "Borussia Dortmund", "GER"],
    ["Konrad Laimer", "MF", "Bayern Munich", "GER"],
    ["Florian Grillitsch", "MF", "Real Sociedad", "ESP"],
    ["Christoph Baumgartner", "MF", "RB Leipzig", "GER"],
    ["Marko Arnautović", "FW", "Inter Milan", "ITA"],
    ["Michael Gregoritsch", "FW", "Freiburg", "GER"],
    ["Romano Schmid", "FW", "Werder Bremen", "GER"],
    ["Patrick Wimmer", "FW", "Wolfsburg", "GER"],
    ["Marco Friedl", "DF", "Werder Bremen", "GER"],
    ["Stefan Posch", "DF", "Bologna", "ITA"],
    ["Alexander Prass", "MF", "Sturm Graz", "AUT"],
    ["Andreas Ulmer", "DF", "Red Bull Salzburg", "AUT"],
    ["Gernot Trauner", "DF", "LASK", "AUT"],
  ],
  JOR: [
    ["Yazeed Abulaila", "GK", "Al-Quwa Al-Jawiya", "IRQ"],
    ["Amir Shafi", "GK", "Al-Faisaly", "JOR"],
    ["Yazan Al-Naimat", "DF", "Al-Ahli", "JOR"],
    ["Husam Al-Taher", "DF", "Al-Wehdat", "JOR"],
    ["Ihsan Haddad", "DF", "Al-Faisaly", "JOR"],
    ["Musab Al-Lawadi", "MF", "Al-Wehdat", "JOR"],
    ["Mahmoud Al-Mardi", "MF", "Al-Faisaly", "JOR"],
    ["Ali Olwan", "MF", "Al-Faisaly", "JOR"],
    ["Mousa Al-Taamari", "FW", "Montpellier", "FRA"],
    ["Yazan Al-Naimat", "FW", "Al-Ahli", "JOR"],
    ["Ali Olwan", "FW", "Al-Faisaly", "JOR"],
    ["Mahmoud Al-Mardi", "FW", "Al-Faisaly", "JOR"],
    ["Ahmad Ersan", "MF", "Al-Wehdat", "JOR"],
    ["Yazan Al-Naimat", "MF", "Al-Ahli", "JOR"],
    ["Baha Abdel-Rahman", "MF", "Al-Faisaly", "JOR"],
    ["Anas Bani Yaseen", "DF", "Al-Faisaly", "JOR"],
    ["Yazan Al-Naimat", "DF", "Al-Ahli", "JOR"],
    ["Musab Al-Lawadi", "FW", "Al-Wehdat", "JOR"],
  ],
  POR: [
    ["Diogo Costa", "GK", "Porto", "POR"],
    ["José Sá", "GK", "Wolverhampton", "ENG"],
    ["Rúben Dias", "DF", "Manchester City", "ENG"],
    ["Nuno Mendes", "DF", "Paris Saint-Germain", "FRA"],
    ["João Cancelo", "DF", "Al-Hilal", "KSA"],
    ["Bruno Fernandes", "MF", "Manchester United", "ENG"],
    ["Bernardo Silva", "MF", "Manchester City", "ENG"],
    ["Vitinha", "MF", "Paris Saint-Germain", "FRA"],
    ["Cristiano Ronaldo", "FW", "Al-Nassr", "KSA"],
    ["Rafael Leão", "FW", "Milan", "ITA"],
    ["Diogo Jota", "FW", "Liverpool", "ENG"],
    ["Gonçalo Ramos", "FW", "Paris Saint-Germain", "FRA"],
    ["João Félix", "FW", "Chelsea", "ENG"],
    ["Pedro Neto", "FW", "Chelsea", "ENG"],
    ["Francisco Conceição", "FW", "Porto", "POR"],
    ["Otávio", "MF", "Al-Nassr", "KSA"],
    ["Rúben Neves", "MF", "Al-Hilal", "KSA"],
    ["Pepe", "DF", "Porto", "POR"],
  ],
  COD: [
    ["Joël Kiassumbua", "GK", "Lugano", "SUI"],
    ["Parfait Mandanda", "GK", "RS Berkane", "MAR"],
    ["Chancel Mbemba", "DF", "Marseille", "FRA"],
    ["Christian Luyindama", "DF", "Standard Liège", "BEL"],
    ["Arthur Masuaku", "DF", "Sunderland", "ENG"],
    ["Gaël Kakuta", "MF", "Amiens", "FRA"],
    ["Edo Kayembe", "MF", "Watford", "ENG"],
    ["Théo Bongonda", "FW", "Standard Liège", "BEL"],
    ["Yoane Wissa", "FW", "Brentford", "ENG"],
    ["Cédric Bakambu", "FW", "Real Betis", "ESP"],
    ["Fiston Mayele", "FW", "Pyramids", "EGY"],
    ["Miché Mika", "FW", "RS Berkane", "MAR"],
    ["Beni Baningime", "MF", "Heart of Midlothian", "SCO"],
    ["Samuel Moutoussamy", "MF", "Changchun Yatai", "CHN"],
    ["Paul-José M'Poku", "FW", "Ankaragücü", "TUR"],
    ["Gael Kakuta", "MF", "Amiens", "FRA"],
    ["Chancel Mbemba", "MF", "Marseille", "FRA"],
    ["Yoane Wissa", "MF", "Brentford", "ENG"],
  ],
  UZB: [
    ["Utkir Yusupov", "GK", "Pakhtakor", "UZB"],
    ["Rustam Yatimov", "GK", "Pakhtakor", "UZB"],
    ["Egor Krimets", "DF", "Pakhtakor", "UZB"],
    ["Abdukakhkhor Abdumavlonov", "DF", "Nasaf", "UZB"],
    ["Jaloliddin Masharipov", "MF", "Al-Nassr", "KSA"],
    ["Odil Ahmedov", "MF", "Pakhtakor", "UZB"],
    ["Jasurbek Yakhshibekov", "MF", "Nasaf", "UZB"],
    ["Eldor Shomurodov", "FW", "Roma", "ITA"],
    ["Igor Sergeev", "FW", "Pakhtakor", "UZB"],
    ["Abbosbek Fayzullaev", "FW", "CSKA Moscow", "RUS"],
    ["Otabek Shukurov", "MF", "Sharjah", "UAE"],
    ["Sanjar Tursunov", "FW", "Nasaf", "UZB"],
    ["Azizbek Turgunboev", "FW", "Pakhtakor", "UZB"],
    ["Jasurbek Yakhshibekov", "FW", "Nasaf", "UZB"],
    ["Khozhimat Erkinov", "MF", "Pakhtakor", "UZB"],
    ["Sherzod Nasriddinov", "DF", "Nasaf", "UZB"],
    ["Odil Abdurakhmanov", "DF", "Pakhtakor", "UZB"],
    ["Rustam Yatimov", "MF", "Pakhtakor", "UZB"],
  ],
  COL: [
    ["Camilo Vargas", "GK", "Atlas", "MEX"],
    ["David Ospina", "GK", "Al-Nassr", "KSA"],
    ["Davinson Sánchez", "DF", "Galatasaray", "TUR"],
    ["Yerry Mina", "DF", "Cagliari", "ITA"],
    ["Johan Mojica", "DF", "Mallorca", "ESP"],
    ["James Rodríguez", "MF", "León", "MEX"],
    ["Luis Díaz", "FW", "Liverpool", "ENG"],
    ["Luis Sinisterra", "FW", "Bournemouth", "ENG"],
    ["Rafael Borré", "FW", "Internacional", "BRA"],
    ["Jhon Durán", "FW", "Aston Villa", "ENG"],
    ["Sebastián Villa", "FW", "Boca Juniors", "ARG"],
    ["Jefferson Lerma", "MF", "Crystal Palace", "ENG"],
    ["Wilmar Barrios", "MF", "Zenit", "RUS"],
    ["Jhon Arias", "MF", "Fluminense", "BRA"],
    ["Jhon Lucumí", "DF", "Bologna", "ITA"],
    ["Santiago Arias", "DF", "América", "MEX"],
    ["Mateus Uribe", "MF", "Monterrey", "MEX"],
    ["Jhon Cordoba", "FW", "Krasnodar", "RUS"],
  ],
  ENG: [
    ["Jordan Pickford", "GK", "Everton", "ENG"],
    ["Nick Pope", "GK", "Newcastle United", "ENG"],
    ["John Stones", "DF", "Manchester City", "ENG"],
    ["Harry Maguire", "DF", "Manchester United", "ENG"],
    ["Kyle Walker", "DF", "Manchester City", "ENG"],
    ["Declan Rice", "MF", "Arsenal", "ENG"],
    ["Jude Bellingham", "MF", "Real Madrid", "ESP"],
    ["Phil Foden", "MF", "Manchester City", "ENG"],
    ["Harry Kane", "FW", "Bayern Munich", "GER"],
    ["Bukayo Saka", "FW", "Arsenal", "ENG"],
    ["Ollie Watkins", "FW", "Aston Villa", "ENG"],
    ["Anthony Gordon", "FW", "Newcastle United", "ENG"],
    ["Cole Palmer", "FW", "Chelsea", "ENG"],
    ["Ivan Toney", "FW", "Al-Ahli", "KSA"],
    ["Jack Grealish", "FW", "Manchester City", "ENG"],
    ["Trent Alexander-Arnold", "DF", "Liverpool", "ENG"],
    ["Kobbie Mainoo", "MF", "Manchester United", "ENG"],
    ["Ezri Konsa", "DF", "Aston Villa", "ENG"],
  ],
  CRO: [
    ["Dominik Livaković", "GK", "Fenerbahçe", "TUR"],
    ["Lovro Kalinić", "GK", "Hajduk Split", "CRO"],
    ["Joško Gvardiol", "DF", "Manchester City", "ENG"],
    ["Dejan Lovren", "DF", "Fenerbahçe", "TUR"],
    ["Borna Sosa", "DF", "Torino", "ITA"],
    ["Luka Modrić", "MF", "Real Madrid", "ESP"],
    ["Mateo Kovačić", "MF", "Manchester City", "ENG"],
    ["Marcelo Brozović", "MF", "Al-Nassr", "KSA"],
    ["Bruno Petković", "FW", "Dinamo Zagreb", "CRO"],
    ["Marko Livaja", "FW", "Hajduk Split", "CRO"],
    ["Ivan Perišić", "FW", "Hajduk Split", "CRO"],
    ["Ante Rebić", "FW", "Beşiktaş", "TUR"],
    ["Mario Pašalić", "MF", "Atalanta", "ITA"],
    ["Luka Sučić", "MF", "Real Sociedad", "ESP"],
    ["Josip Juranović", "DF", "Union Berlin", "GER"],
    ["Martin Baturina", "MF", "Dinamo Zagreb", "CRO"],
    ["Nikola Vlašić", "MF", "Torino", "ITA"],
    ["Pepe", "DF", "Porto", "POR"],
  ],
  GHA: [
    ["Lawrence Ati-Zigi", "GK", "St. Gallen", "SUI"],
    ["Richard Ofori", "GK", "Kaizer Chiefs", "RSA"],
    ["Daniel Amartey", "DF", "Leicester City", "ENG"],
    ["Alexander Djiku", "DF", "Fenerbahçe", "TUR"],
    ["Gideon Mensah", "DF", "Auxerre", "FRA"],
    ["Thomas Partey", "MF", "Arsenal", "ENG"],
    ["Mohammed Kudus", "MF", "West Ham", "ENG"],
    ["Salis Abdul Samed", "MF", "Lens", "FRA"],
    ["André Ayew", "FW", "Le Havre", "FRA"],
    ["Jordan Ayew", "FW", "Leicester City", "ENG"],
    ["Inaki Williams", "FW", "Athletic Club", "ESP"],
    ["Antoine Semenyo", "FW", "Bournemouth", "ENG"],
    ["Ernest Nuamah", "FW", "Lyon", "FRA"],
    ["Kamaldeen Sulemana", "FW", "Southampton", "ENG"],
    ["Joseph Paintsil", "FW", "LA Galaxy", "USA"],
    ["Daniel-Kofi Kyereh", "MF", "Freiburg", "GER"],
    ["Alidu Seidu", "DF", "Rennes", "FRA"],
    ["Baba Idrissu", "MF", "Viborg", "DEN"],
  ],
  PAN: [
    ["Jaime Penedo", "GK", "Dinamo București", "ROU"],
    ["Luis Mejía", "GK", "Nacional", "URY"],
    ["Michael Murillo", "DF", "Marseille", "FRA"],
    ["Fidel Escobar", "DF", "Al-Adalah", "KSA"],
    ["Harold Cummings", "DF", "Saprissa", "PAN"],
    ["Aníbal Godoy", "MF", "Nashville SC", "USA"],
    ["Adalberto Carrasquilla", "MF", "Houston Dynamo", "USA"],
    ["José Fajardo", "FW", "Saprissa", "PAN"],
    ["Ismael Díaz", "FW", "Mazatlán", "MEX"],
    ["Alberto Quintero", "FW", "Universitario", "PER"],
    ["Gabriel Torres", "FW", "The Strongest", "BOL"],
    ["Rolando Blackburn", "FW", "The Strongest", "BOL"],
    ["César Blackman", "MF", "Dunaj Streda", "SVK"],
    ["Jorge Gómez", "DF", "Comunicaciones", "GUA"],
    ["José Luis Rodríguez", "MF", "Deportivo Saprissa", "PAN"],
    ["Omar Browne", "FW", "Independiente", "PAN"],
    ["Ricardo Ávila", "MF", "Gent", "BEL"],
    ["Ismael Díaz", "MF", "Mazatlán", "MEX"],
  ],
};
