/**
 * Projected WC 2026 squad-style rosters for 48 group-phase nations.
 * Source: FIFA official squads (published June 2, 2026) via Wikipedia
 *   https://en.wikipedia.org/wiki/2026_FIFA_World_Cup_squads
 * Regenerate seed: node scripts/generate-players-seed.mjs
 */
export const PLAYER_SQUADS = {
  MEX: [
    ["Raúl Rangel", "GK", "Guadalajara", "MEX"],
    ["Carlos Acevedo", "GK", "Santos Laguna", "MEX"],
    ["Guillermo Ochoa", "GK", "AEL Limassol", "CYP"],
    ["Jorge Sánchez", "DF", "PAOK", "GRE"],
    ["César Montes", "DF", "Lokomotiv Moscow", "RUS"],
    ["Edson Álvarez", "DF", "Fenerbahçe", "TUR"],
    ["Johan Vásquez", "DF", "Genoa", "ITA"],
    ["Israel Reyes", "DF", "América", "MEX"],
    ["Érik Lira", "MF", "Cruz Azul", "MEX"],
    ["Luis Romo", "MF", "Guadalajara", "MEX"],
    ["Álvaro Fidalgo", "MF", "Real Betis", "ESP"],
    ["Orbelín Pineda", "MF", "AEK Athens", "GRE"],
    ["Obed Vargas", "MF", "Atlético Madrid", "ESP"],
    ["Raúl Jiménez", "FW", "Fulham", "ENG"],
    ["Alexis Vega", "FW", "Toluca", "MEX"],
    ["Santiago Giménez", "FW", "Milan", "ITA"],
    ["Armando González", "FW", "Guadalajara", "MEX"],
    ["Julián Quiñones", "FW", "Al-Qadsiah", "KSA"],
  ],
  RSA: [
    ["Ronwen Williams", "GK", "Mamelodi Sundowns", "RSA"],
    ["Sipho Chaine", "GK", "Orlando Pirates", "RSA"],
    ["Ricardo Goss", "GK", "Siwelele", "RSA"],
    ["Thabang Matuludi", "DF", "Polokwane City", "RSA"],
    ["Khulumani Ndamane", "DF", "Mamelodi Sundowns", "RSA"],
    ["Aubrey Modiba", "DF", "Mamelodi Sundowns", "RSA"],
    ["Mbekezeli Mbokazi", "DF", "Chicago Fire FC", "USA"],
    ["Samukele Kabini", "DF", "Molde", "NOR"],
    ["Teboho Mokoena", "MF", "Mamelodi Sundowns", "RSA"],
    ["Thalente Mbatha", "MF", "Orlando Pirates", "RSA"],
    ["Themba Zwane", "MF", "Mamelodi Sundowns", "RSA"],
    ["Sphephelo Sithole", "MF", "Tondela", "POR"],
    ["Jayden Adams", "MF", "Mamelodi Sundowns", "RSA"],
    ["Oswin Appollis", "FW", "Orlando Pirates", "RSA"],
    ["Tshepang Moremi", "FW", "Orlando Pirates", "RSA"],
    ["Lyle Foster", "FW", "Burnley", "ENG"],
    ["Relebohile Mofokeng", "FW", "Orlando Pirates", "RSA"],
    ["Thapelo Maseko", "FW", "AEL Limassol", "CYP"],
  ],
  KOR: [
    ["Kim Seung-gyu", "GK", "FC Tokyo", "JPN"],
    ["Song Bum-keun", "GK", "Jeonbuk Hyundai Motors", "KOR"],
    ["Jo Hyeon-woo", "GK", "Ulsan HD", "KOR"],
    ["Lee Han-beom", "DF", "Midtjylland", "DEN"],
    ["Kim Min-jae", "DF", "Bayern Munich", "GER"],
    ["Kim Tae-hyeon", "DF", "Kashima Antlers", "JPN"],
    ["Lee Tae-seok", "DF", "Austria Wien", "KOR"],
    ["Cho Wi-je", "DF", "Jeonbuk Hyundai Motors", "KOR"],
    ["Lee Gi-hyuk", "MF", "Gangwon FC", "KOR"],
    ["Hwang In-beom", "MF", "Feyenoord", "NED"],
    ["Paik Seung-ho", "MF", "Birmingham City", "ENG"],
    ["Lee Jae-sung", "MF", "Mainz 05", "GER"],
    ["Hwang Hee-chan", "MF", "Wolverhampton Wanderers", "ENG"],
    ["Son Heung-min", "FW", "Los Angeles FC", "USA"],
    ["Cho Gue-sung", "FW", "Midtjylland", "DEN"],
    ["Oh Hyeon-gyu", "FW", "Beşiktaş", "TUR"],
    ["Kim Moon-hwan", "DF", "Daejeon Hana Citizen", "KOR"],
    ["Park Jin-seob", "DF", "Zhejiang", "KOR"],
  ],
  CZE: [
    ["Matěj Kovář", "GK", "PSV Eindhoven", "NED"],
    ["Jindřich Staněk", "GK", "Slavia Prague", "CZE"],
    ["Lukáš Horníček", "GK", "Braga", "POR"],
    ["David Zima", "DF", "Slavia Prague", "CZE"],
    ["Tomáš Holeš", "DF", "Slavia Prague", "CZE"],
    ["Robin Hranáč", "DF", "TSG Hoffenheim", "GER"],
    ["Vladimír Coufal", "DF", "TSG Hoffenheim", "GER"],
    ["Štěpán Chaloupek", "DF", "Slavia Prague", "CZE"],
    ["Ladislav Krejčí", "DF", "Wolverhampton Wanderers", "ENG"],
    ["Vladimír Darida", "MF", "Hradec Králové", "CZE"],
    ["Lukáš Červ", "MF", "Viktoria Plzeň", "CZE"],
    ["Lukáš Provod", "MF", "Slavia Prague", "CZE"],
    ["Michal Sadílek", "MF", "Slavia Prague", "CZE"],
    ["Tomáš Souček", "MF", "West Ham United", "ENG"],
    ["Adam Hložek", "FW", "TSG Hoffenheim", "GER"],
    ["Patrik Schick", "FW", "Bayer Leverkusen", "GER"],
    ["Jan Kuchta", "FW", "Sparta Prague", "CZE"],
    ["Mojmír Chytil", "FW", "Slavia Prague", "CZE"],
    ["Pavel Šulc", "FW", "Lyon", "FRA"],
  ],
  CAN: [
    ["Dayne St. Clair", "GK", "Inter Miami CF", "USA"],
    ["Maxime Crépeau", "GK", "Orlando City SC", "USA"],
    ["Owen Goodman", "GK", "Barnsley", "CAN"],
    ["Alistair Johnston", "DF", "Celtic", "SCO"],
    ["Alfie Jones", "DF", "Middlesbrough", "ENG"],
    ["Luc de Fougerolles", "DF", "Dender", "CAN"],
    ["Joel Waterman", "DF", "Chicago Fire FC", "USA"],
    ["Derek Cornelius", "DF", "Rangers", "SCO"],
    ["Mathieu Choinière", "MF", "Los Angeles FC", "USA"],
    ["Stephen Eustáquio", "MF", "Los Angeles FC", "USA"],
    ["Ismaël Koné", "MF", "Sassuolo", "ITA"],
    ["Liam Millar", "MF", "Hull City", "ENG"],
    ["Jacob Shaffelburg", "MF", "Los Angeles FC", "USA"],
    ["Cyle Larin", "FW", "Southampton", "ENG"],
    ["Jonathan David", "FW", "Juventus", "ITA"],
    ["Tani Oluwaseyi", "FW", "Villarreal", "ESP"],
    ["Tajon Buchanan", "FW", "Villarreal", "ESP"],
    ["Ali Ahmed", "FW", "Norwich City", "ENG"],
  ],
  BIH: [
    ["Nikola Vasilj", "GK", "FC St. Pauli", "GER"],
    ["Mladen Jurkas", "GK", "Borac Banja Luka", "BIH"],
    ["Martin Zlomislić", "GK", "Rijeka", "CRO"],
    ["Nihad Mujakić", "DF", "Gaziantep", "TUR"],
    ["Dennis Hadžikadunić", "DF", "Sampdoria", "ITA"],
    ["Tarik Muharemović", "DF", "Sassuolo", "ITA"],
    ["Sead Kolašinac", "DF", "Atalanta", "ITA"],
    ["Amar Dedić", "DF", "Benfica", "POR"],
    ["Benjamin Tahirović", "MF", "Brøndby", "BIH"],
    ["Armin Gigović", "MF", "Young Boys", "SUI"],
    ["Ivan Bašić", "MF", "Astana", "KAZ"],
    ["Ivan Šunjić", "MF", "Pafos", "BIH"],
    ["Amar Memić", "MF", "Viktoria Plzeň", "CZE"],
    ["Samed Baždar", "FW", "Jagiellonia Białystok", "BIH"],
    ["Ermedin Demirović", "FW", "VfB Stuttgart", "GER"],
    ["Edin Džeko", "FW", "Schalke 04", "GER"],
    ["Kerim Alajbegović", "FW", "Red Bull Salzburg", "AUT"],
    ["Esmir Bajraktarević", "FW", "PSV Eindhoven", "NED"],
    ["Jovo Lukić", "FW", "FC Universitatea Cluj", "ROU"],
  ],
  QAT: [
    ["Mahmud Abunada", "GK", "Al-Rayyan", "QAT"],
    ["Salah Zakaria", "GK", "Al-Duhail", "QAT"],
    ["Meshaal Barsham", "GK", "Al-Sadd", "QAT"],
    ["Pedro Miguel", "DF", "Al-Sadd", "QAT"],
    ["Lucas Mendes", "DF", "Al-Wakrah", "QAT"],
    ["Issa Laye", "DF", "Al-Arabi", "QAT"],
    ["Jassem Gaber", "DF", "Al-Rayyan", "QAT"],
    ["Ayoub Al-Oui", "DF", "Al-Gharafa", "QAT"],
    ["Abdulaziz Hatem", "MF", "Al-Rayyan", "QAT"],
    ["Karim Boudiaf", "MF", "Al-Duhail", "QAT"],
    ["Ahmed Al-Ganehi", "MF", "Al-Gharafa", "QAT"],
    ["Ahmed Fathy", "MF", "Al-Arabi", "QAT"],
    ["Assim Madibo", "MF", "Al-Wakrah", "QAT"],
    ["Ahmed Alaaeldin", "FW", "Al-Rayyan", "QAT"],
    ["Edmilson Junior", "FW", "Al-Duhail", "QAT"],
    ["Mohammed Muntari", "FW", "Al-Gharafa", "QAT"],
    ["Hassan Al-Haydos", "FW", "Al-Sadd", "QAT"],
    ["Akram Afif", "FW", "Al-Sadd", "QAT"],
  ],
  SUI: [
    ["Gregor Kobel", "GK", "Borussia Dortmund", "GER"],
    ["Yvon Mvogo", "GK", "Lorient", "FRA"],
    ["Marvin Keller", "GK", "Young Boys", "SUI"],
    ["Miro Muheim", "DF", "Hamburger SV", "GER"],
    ["Silvan Widmer", "DF", "Mainz 05", "GER"],
    ["Nico Elvedi", "DF", "Borussia Mönchengladbach", "GER"],
    ["Manuel Akanji", "DF", "Inter Milan", "ITA"],
    ["Ricardo Rodriguez", "DF", "Real Betis", "ESP"],
    ["Denis Zakaria", "MF", "Monaco", "FRA"],
    ["Remo Freuler", "MF", "Bologna", "ITA"],
    ["Johan Manzambi", "MF", "SC Freiburg", "GER"],
    ["Granit Xhaka", "MF", "Sunderland", "ENG"],
    ["Ardon Jashari", "MF", "Milan", "ITA"],
    ["Breel Embolo", "FW", "Rennes", "FRA"],
    ["Dan Ndoye", "FW", "Nottingham Forest", "ENG"],
    ["Christian Fassnacht", "FW", "Young Boys", "SUI"],
    ["Rubén Vargas", "FW", "Sevilla", "ESP"],
    ["Noah Okafor", "FW", "Leeds United", "ENG"],
  ],
  BRA: [
    ["Alisson", "GK", "Liverpool", "ENG"],
    ["Weverton", "GK", "Grêmio", "BRA"],
    ["Ederson Moraes", "GK", "Fenerbahçe", "TUR"],
    ["Gabriel Magalhães", "DF", "Arsenal", "ENG"],
    ["Marquinhos", "DF", "Paris Saint-Germain", "FRA"],
    ["Alex Sandro", "DF", "Flamengo", "BRA"],
    ["Danilo Luiz", "DF", "Flamengo", "BRA"],
    ["Bremer", "DF", "Juventus", "ITA"],
    ["Éderson Silva", "MF", "Atalanta", "ITA"],
    ["Casemiro", "MF", "Manchester United", "ENG"],
    ["Bruno Guimarães", "MF", "Newcastle United", "ENG"],
    ["Fabinho", "MF", "Al-Ittihad", "KSA"],
    ["Danilo Santos", "MF", "Botafogo", "BRA"],
    ["Vinícius Júnior", "FW", "Real Madrid", "ESP"],
    ["Matheus Cunha", "FW", "Manchester United", "ENG"],
    ["Neymar", "FW", "Santos", "BRA"],
    ["Raphinha", "FW", "Barcelona", "ESP"],
    ["Endrick", "FW", "Lyon", "FRA"],
  ],
  MAR: [
    ["Yassine Bounou", "GK", "Al-Hilal", "KSA"],
    ["Munir Mohamedi", "GK", "RS Berkane", "MAR"],
    ["Ahmed Reda Tagnaouti", "GK", "AS FAR", "MAR"],
    ["Achraf Hakimi", "DF", "Paris Saint-Germain", "FRA"],
    ["Noussair Mazraoui", "DF", "Manchester United", "ENG"],
    ["Marwane Saâdane", "DF", "Al-Fateh", "KSA"],
    ["Zakaria El Ouahdi", "DF", "Genk", "BEL"],
    ["Issa Diop", "DF", "Fulham", "ENG"],
    ["Sofyan Amrabat", "MF", "Real Betis", "ESP"],
    ["Ayyoub Bouaddi", "MF", "Lille", "FRA"],
    ["Chemsdine Talbi", "MF", "Sunderland", "ENG"],
    ["Azzedine Ounahi", "MF", "Girona", "MAR"],
    ["Ismael Saibari", "MF", "PSV Eindhoven", "NED"],
    ["Soufiane Rahimi", "FW", "Al Ain", "UAE"],
    ["Brahim Díaz", "FW", "Real Madrid", "ESP"],
    ["Amine Sbaï", "FW", "Angers", "FRA"],
    ["Ayoub El Kaabi", "FW", "Olympiacos", "GRE"],
    ["Ayoube Amaimouni", "FW", "Eintracht Frankfurt", "GER"],
  ],
  HAI: [
    ["Johny Placide", "GK", "Bastia", "HAI"],
    ["Alexandre Pierre", "GK", "Sochaux", "HAI"],
    ["Josué Duverger", "GK", "Cosmos Koblenz", "HAI"],
    ["Carlens Arcus", "DF", "Angers", "FRA"],
    ["Keeto Thermoncy", "DF", "Young Boys", "SUI"],
    ["Ricardo Adé", "DF", "LDU Quito", "ECU"],
    ["Hannes Delcroix", "DF", "Lugano", "SUI"],
    ["Martin Expérience", "DF", "Nancy", "HAI"],
    ["Carl Sainté", "MF", "El Paso Locomotive FC", "USA"],
    ["Jean-Ricner Bellegarde", "MF", "Wolverhampton Wanderers", "ENG"],
    ["Danley Jean Jacques", "MF", "Philadelphia Union", "USA"],
    ["Dominique Simon", "MF", "Tatran Prešov", "HAI"],
    ["Woodensky Pierre", "MF", "Violette", "HAI"],
    ["Derrick Etienne Jr.", "FW", "Toronto FC", "CAN"],
    ["Duckens Nazon", "FW", "Esteghlal", "IRN"],
    ["Louicius Deedson", "FW", "FC Dallas", "USA"],
    ["Ruben Providence", "FW", "Almere City", "NED"],
    ["Lenny Joseph", "FW", "Ferencváros", "HAI"],
  ],
  SCO: [
    ["Angus Gunn", "GK", "Nottingham Forest", "ENG"],
    ["Liam Kelly", "GK", "Rangers", "SCO"],
    ["Craig Gordon", "GK", "Heart of Midlothian", "SCO"],
    ["Aaron Hickey", "DF", "Brentford", "ENG"],
    ["Andy Robertson", "DF", "Liverpool", "ENG"],
    ["Grant Hanley", "DF", "Hibernian", "SCO"],
    ["Kieran Tierney", "DF", "Celtic", "SCO"],
    ["Jack Hendry", "DF", "Al-Ettifaq", "KSA"],
    ["Scott McTominay", "MF", "Napoli", "ITA"],
    ["John McGinn", "MF", "Aston Villa", "ENG"],
    ["Tyler Fletcher", "MF", "Manchester United", "ENG"],
    ["Ryan Christie", "MF", "Bournemouth", "ENG"],
    ["Lewis Ferguson", "MF", "Bologna", "ITA"],
    ["Lyndon Dykes", "FW", "Charlton Athletic", "SCO"],
    ["Ché Adams", "FW", "Torino", "ITA"],
    ["Ross Stewart", "FW", "Southampton", "ENG"],
    ["Ben Gannon-Doak", "FW", "Bournemouth", "ENG"],
    ["George Hirst", "FW", "Ipswich Town", "SCO"],
  ],
  USA: [
    ["Matt Turner", "GK", "New England Revolution", "USA"],
    ["Matt Freese", "GK", "New York City FC", "USA"],
    ["Chris Brady", "GK", "Chicago Fire FC", "USA"],
    ["Sergiño Dest", "DF", "PSV Eindhoven", "NED"],
    ["Chris Richards", "DF", "Crystal Palace", "ENG"],
    ["Antonee Robinson", "DF", "Fulham", "ENG"],
    ["Auston Trusty", "DF", "Celtic", "SCO"],
    ["Miles Robinson", "DF", "FC Cincinnati", "USA"],
    ["Tyler Adams", "MF", "Bournemouth", "ENG"],
    ["Giovanni Reyna", "MF", "Borussia Mönchengladbach", "GER"],
    ["Weston McKennie", "MF", "Juventus", "ITA"],
    ["Sebastian Berhalter", "MF", "Vancouver Whitecaps FC", "CAN"],
    ["Cristian Roldan", "MF", "Seattle Sounders FC", "USA"],
    ["Ricardo Pepi", "FW", "PSV Eindhoven", "NED"],
    ["Christian Pulisic", "FW", "Milan", "ITA"],
    ["Brenden Aaronson", "FW", "Leeds United", "ENG"],
    ["Haji Wright", "FW", "Coventry City", "ENG"],
    ["Folarin Balogun", "FW", "Monaco", "FRA"],
  ],
  PAR: [
    ["Gatito Fernández", "GK", "Cerro Porteño", "PAR"],
    ["Orlando Gill", "GK", "San Lorenzo", "PAR"],
    ["Gastón Olveira", "GK", "Olimpia", "PAR"],
    ["Gustavo Velázquez", "DF", "Cerro Porteño", "PAR"],
    ["Omar Alderete", "DF", "Sunderland", "ENG"],
    ["Juan José Cáceres", "DF", "Dynamo Moscow", "RUS"],
    ["Fabián Balbuena", "DF", "Grêmio", "BRA"],
    ["Júnior Alonso", "DF", "Atlético Mineiro", "BRA"],
    ["Ramón Sosa", "MF", "Palmeiras", "BRA"],
    ["Diego Gómez", "MF", "Brighton & Hove Albion", "ENG"],
    ["Miguel Almirón", "MF", "Atlanta United FC", "USA"],
    ["Maurício", "MF", "Palmeiras", "BRA"],
    ["Andrés Cubas", "MF", "Vancouver Whitecaps FC", "CAN"],
    ["Damián Bobadilla", "MF", "São Paulo", "BRA"],
    ["Antonio Sanabria", "FW", "Cremonese", "PAR"],
    ["Kaku", "FW", "Al Ain", "UAE"],
    ["Álex Arce", "FW", "Independiente Rivadavia", "PAR"],
    ["Julio Enciso", "FW", "Strasbourg", "PAR"],
    ["Gabriel Ávalos", "FW", "Independiente", "PAN"],
  ],
  AUS: [
    ["Mathew Ryan", "GK", "Levante", "AUS"],
    ["Paul Izzo", "GK", "Randers", "AUS"],
    ["Patrick Beach", "GK", "Melbourne City", "AUS"],
    ["Miloš Degenek", "DF", "APOEL", "AUS"],
    ["Alessandro Circati", "DF", "Parma", "ITA"],
    ["Jacob Italiano", "DF", "Grazer AK", "AUS"],
    ["Jordan Bos", "DF", "Feyenoord", "NED"],
    ["Jason Geria", "DF", "Albirex Niigata", "AUS"],
    ["Connor Metcalfe", "MF", "FC St. Pauli", "GER"],
    ["Aiden O\'Neill", "MF", "New York City FC", "USA"],
    ["Cammy Devlin", "MF", "Heart of Midlothian", "SCO"],
    ["Jackson Irvine", "MF", "FC St. Pauli", "GER"],
    ["Paul Okon-Engstler", "MF", "Sydney FC", "AUS"],
    ["Mathew Leckie", "FW", "Melbourne City", "AUS"],
    ["Mohamed Touré", "FW", "Norwich City", "ENG"],
    ["Ajdin Hrustic", "FW", "Heracles Almelo", "AUS"],
    ["Awer Mabil", "FW", "Castellón", "AUS"],
    ["Nestory Irankunda", "FW", "Watford", "ENG"],
  ],
  TUR: [
    ["Mert Günok", "GK", "Fenerbahçe", "TUR"],
    ["Altay Bayındır", "GK", "Manchester United", "ENG"],
    ["Uğurcan Çakır", "GK", "Galatasaray", "TUR"],
    ["Zeki Çelik", "DF", "Roma", "ITA"],
    ["Merih Demiral", "DF", "Al-Ahli", "KSA"],
    ["Çağlar Söyüncü", "DF", "Fenerbahçe", "TUR"],
    ["Eren Elmalı", "DF", "Galatasaray", "TUR"],
    ["Abdülkerim Bardakcı", "DF", "Galatasaray", "TUR"],
    ["Salih Özcan", "MF", "Borussia Dortmund", "GER"],
    ["Orkun Kökçü", "MF", "Beşiktaş", "TUR"],
    ["Hakan Çalhanoğlu", "MF", "Inter Milan", "ITA"],
    ["İsmail Yüksek", "MF", "Fenerbahçe", "TUR"],
    ["Kaan Ayhan", "MF", "Galatasaray", "TUR"],
    ["Kerem Aktürkoğlu", "FW", "Fenerbahçe", "TUR"],
    ["Arda Güler", "FW", "Real Madrid", "ESP"],
    ["Deniz Gül", "FW", "Porto", "POR"],
    ["Kenan Yıldız", "FW", "Juventus", "ITA"],
    ["İrfan Can Kahveci", "FW", "Kasımpaşa", "TUN"],
  ],
  GER: [
    ["Manuel Neuer", "GK", "Bayern Munich", "GER"],
    ["Oliver Baumann", "GK", "TSG Hoffenheim", "GER"],
    ["Alexander Nübel", "GK", "VfB Stuttgart", "GER"],
    ["Antonio Rüdiger", "DF", "Real Madrid", "ESP"],
    ["Waldemar Anton", "DF", "Borussia Dortmund", "GER"],
    ["Jonathan Tah", "DF", "Bayern Munich", "GER"],
    ["Joshua Kimmich", "DF", "Bayern Munich", "GER"],
    ["Nico Schlotterbeck", "DF", "Borussia Dortmund", "GER"],
    ["Aleksandar Pavlović", "MF", "Bayern Munich", "GER"],
    ["Leon Goretzka", "MF", "Bayern Munich", "GER"],
    ["Jamie Leweling", "MF", "VfB Stuttgart", "GER"],
    ["Jamal Musiala", "MF", "Bayern Munich", "GER"],
    ["Pascal Groß", "MF", "Brighton & Hove Albion", "ENG"],
    ["Kai Havertz", "FW", "Arsenal", "ENG"],
    ["Nick Woltemade", "FW", "Newcastle United", "ENG"],
    ["Maximilian Beier", "FW", "Borussia Dortmund", "GER"],
    ["Deniz Undav", "FW", "VfB Stuttgart", "GER"],
    ["Angelo Stiller", "MF", "VfB Stuttgart", "GER"],
  ],
  CUW: [
    ["Eloy Room", "GK", "Miami FC", "USA"],
    ["Tyrick Bodak", "GK", "Telstar", "CUW"],
    ["Trevor Doornbusch", "GK", "VVV-Venlo", "CUW"],
    ["Shurandy Sambo", "DF", "Sparta Rotterdam", "NED"],
    ["Juriën Gaari", "DF", "Abha", "CUW"],
    ["Roshon van Eijma", "DF", "RKC Waalwijk", "CUW"],
    ["Sherel Floranus", "DF", "PEC Zwolle", "CUW"],
    ["Armando Obispo", "DF", "PSV Eindhoven", "NED"],
    ["Godfried Roemeratoe", "MF", "RKC Waalwijk", "CUW"],
    ["Juninho Bacuna", "MF", "Volendam", "NED"],
    ["Livano Comenencia", "MF", "Zürich", "CUW"],
    ["Leandro Bacuna", "MF", "Iğdır", "CUW"],
    ["Ar\'jany Martha", "MF", "Rotherham United", "CUW"],
    ["Jürgen Locadia", "FW", "Miami FC", "USA"],
    ["Jeremy Antonisse", "FW", "Kifisia", "CUW"],
    ["Sontje Hansen", "FW", "Middlesbrough", "ENG"],
    ["Tyrese Noslin", "FW", "Telstar", "CUW"],
    ["Kenji Gorré", "FW", "Maccabi Haifa", "CUW"],
  ],
  CIV: [
    ["Yahia Fofana", "GK", "Çaykur Rizespor", "CIV"],
    ["Mohamed Koné", "GK", "Charleroi", "CIV"],
    ["Alban Lafont", "GK", "Panathinaikos", "GRE"],
    ["Ousmane Diomande", "DF", "Sporting CP", "POR"],
    ["Ghislain Konan", "DF", "Gil Vicente", "CIV"],
    ["Wilfried Singo", "DF", "Galatasaray", "TUR"],
    ["Odilon Kossounou", "DF", "Atalanta", "ITA"],
    ["Christopher Opéri", "DF", "İstanbul Başakşehir", "TUR"],
    ["Jean Michaël Seri", "MF", "Maribor", "CIV"],
    ["Seko Fofana", "MF", "Porto", "POR"],
    ["Franck Kessié", "MF", "Al-Ahli", "KSA"],
    ["Ibrahim Sangaré", "MF", "Nottingham Forest", "ENG"],
    ["Parfait Guiagon", "MF", "Charleroi", "CIV"],
    ["Ange-Yoan Bonny", "FW", "Inter Milan", "ITA"],
    ["Simon Adingra", "FW", "Monaco", "FRA"],
    ["Yan Diomande", "FW", "RB Leipzig", "GER"],
    ["Elye Wahi", "FW", "Nice", "FRA"],
    ["Oumar Diakité", "FW", "Cercle Brugge", "CIV"],
  ],
  ECU: [
    ["Hernán Galíndez", "GK", "Huracán", "ECU"],
    ["Moisés Ramírez", "GK", "Kifisia", "CUW"],
    ["Gonzalo Valle", "GK", "LDU Quito", "ECU"],
    ["Félix Torres", "DF", "Internacional", "BRA"],
    ["Piero Hincapié", "DF", "Arsenal", "ENG"],
    ["Joel Ordóñez", "DF", "Club Brugge", "BEL"],
    ["Willian Pacho", "DF", "Paris Saint-Germain", "FRA"],
    ["Pervis Estupiñán", "DF", "Milan", "ITA"],
    ["Jordy Alcívar", "MF", "Independiente del Valle", "ECU"],
    ["Anthony Valencia", "MF", "Antwerp", "BEL"],
    ["Kendry Páez", "MF", "River Plate", "ARG"],
    ["Alan Minda", "MF", "Atlético Mineiro", "BRA"],
    ["Pedro Vite", "MF", "Pumas", "ECU"],
    ["John Yeboah", "FW", "Venezia", "ECU"],
    ["Kevin Rodríguez", "FW", "Union Saint-Gilloise", "BEL"],
    ["Enner Valencia", "FW", "Pachuca", "ECU"],
    ["Jordy Caicedo", "FW", "Huracán", "ECU"],
    ["Gonzalo Plata", "FW", "Flamengo", "BRA"],
  ],
  NED: [
    ["Bart Verbruggen", "GK", "Brighton & Hove Albion", "ENG"],
    ["Robin Roefs", "GK", "Sunderland", "ENG"],
    ["Mark Flekken", "GK", "Bayer Leverkusen", "GER"],
    ["Lutsharel Geertruida", "DF", "Sunderland", "ENG"],
    ["Virgil van Dijk", "DF", "Liverpool", "ENG"],
    ["Nathan Aké", "DF", "Manchester City", "ENG"],
    ["Jan Paul van Hecke", "DF", "Brighton & Hove Albion", "ENG"],
    ["Mats Wieffer", "DF", "Brighton & Hove Albion", "ENG"],
    ["Marten de Roon", "MF", "Atalanta", "ITA"],
    ["Justin Kluivert", "MF", "Bournemouth", "ENG"],
    ["Ryan Gravenberch", "MF", "Liverpool", "ENG"],
    ["Tijjani Reijnders", "MF", "Manchester City", "ENG"],
    ["Guus Til", "MF", "PSV Eindhoven", "NED"],
    ["Wout Weghorst", "FW", "Ajax", "NED"],
    ["Memphis Depay", "FW", "Corinthians", "BRA"],
    ["Cody Gakpo", "FW", "Liverpool", "ENG"],
    ["Noa Lang", "FW", "Galatasaray", "TUR"],
    ["Donyell Malen", "FW", "Roma", "ITA"],
  ],
  JPN: [
    ["Zion Suzuki", "GK", "Parma", "ITA"],
    ["Keisuke Ōsako", "GK", "Sanfrecce Hiroshima", "JPN"],
    ["Tomoki Hayakawa", "GK", "Kashima Antlers", "JPN"],
    ["Yukinari Sugawara", "DF", "Werder Bremen", "GER"],
    ["Shōgo Taniguchi", "DF", "Sint-Truiden", "BEL"],
    ["Kō Itakura", "DF", "Ajax", "NED"],
    ["Yūto Nagatomo", "DF", "FC Tokyo", "JPN"],
    ["Tsuyoshi Watanabe", "DF", "Feyenoord", "NED"],
    ["Ao Tanaka", "MF", "Leeds United", "ENG"],
    ["Takefusa Kubo", "MF", "Real Sociedad", "ESP"],
    ["Ritsu Dōan", "MF", "Eintracht Frankfurt", "GER"],
    ["Daizen Maeda", "MF", "Celtic", "SCO"],
    ["Keito Nakamura", "MF", "Reims", "FRA"],
    ["Shūto Machino", "FW", "Borussia Mönchengladbach", "GER"],
    ["Keisuke Gotō", "FW", "Sint-Truiden", "BEL"],
    ["Ayase Ueda", "FW", "Feyenoord", "NED"],
    ["Kōki Ogawa", "FW", "NEC", "NED"],
    ["Kento Shiogai", "FW", "VfL Wolfsburg", "GER"],
  ],
  SWE: [
    ["Jacob Widell Zetterström", "GK", "Derby County", "SWE"],
    ["Viktor Johansson", "GK", "Stoke City", "ENG"],
    ["Kristoffer Nordfeldt", "GK", "AIK", "SWE"],
    ["Gustaf Lagerbielke", "DF", "Braga", "POR"],
    ["Victor Lindelöf", "DF", "Aston Villa", "ENG"],
    ["Isak Hien", "DF", "Atalanta", "ITA"],
    ["Gabriel Gudmundsson", "DF", "Leeds United", "ENG"],
    ["Herman Johansson", "DF", "FC Dallas", "USA"],
    ["Lucas Bergvall", "MF", "Tottenham Hotspur", "ENG"],
    ["Benjamin Nygren", "MF", "Celtic", "SCO"],
    ["Ken Sema", "MF", "Pafos", "BIH"],
    ["Jesper Karlström", "MF", "Udinese", "ITA"],
    ["Yasin Ayari", "MF", "Brighton & Hove Albion", "ENG"],
    ["Alexander Isak", "FW", "Liverpool", "ENG"],
    ["Anthony Elanga", "FW", "Newcastle United", "ENG"],
    ["Viktor Gyökeres", "FW", "Arsenal", "ENG"],
    ["Gustaf Nilsson", "FW", "Club Brugge", "BEL"],
    ["Taha Ali", "FW", "Malmö FF", "SWE"],
  ],
  TUN: [
    ["Mouhib Chamakh", "GK", "Club Africain", "TUN"],
    ["Aymen Dahmen", "GK", "CS Sfaxien", "TUN"],
    ["Sabri Ben Hessen", "GK", "Étoile du Sahel", "TUN"],
    ["Ali Abdi", "DF", "Nice", "FRA"],
    ["Montassar Talbi", "DF", "Lorient", "FRA"],
    ["Omar Rekik", "DF", "Maribor", "CIV"],
    ["Adem Arous", "DF", "Kasımpaşa", "TUN"],
    ["Dylan Bronn", "DF", "Servette", "SUI"],
    ["Hannibal Mejbri", "MF", "Burnley", "ENG"],
    ["Ismaël Gharbi", "MF", "FC Augsburg", "TUN"],
    ["Rani Khedira", "MF", "Union Berlin", "GER"],
    ["Khalil Ayari", "MF", "Paris Saint-Germain", "FRA"],
    ["Hadj Mahmoud", "MF", "Lugano", "SUI"],
    ["Elias Achouri", "FW", "Copenhagen", "DEN"],
    ["Elias Saad", "FW", "Hannover 96", "GER"],
    ["Hazem Mastouri", "FW", "Dynamo Makhachkala", "TUN"],
    ["Rayan Elloumi", "FW", "Vancouver Whitecaps FC", "CAN"],
    ["Firas Chaouat", "FW", "Club Africain", "TUN"],
  ],
  BEL: [
    ["Thibaut Courtois", "GK", "Real Madrid", "ESP"],
    ["Senne Lammens", "GK", "Manchester United", "ENG"],
    ["Mike Penders", "GK", "Strasbourg", "PAR"],
    ["Zeno Debast", "DF", "Sporting CP", "POR"],
    ["Arthur Theate", "DF", "Eintracht Frankfurt", "GER"],
    ["Brandon Mechele", "DF", "Club Brugge", "BEL"],
    ["Maxim De Cuyper", "DF", "Brighton & Hove Albion", "ENG"],
    ["Thomas Meunier", "DF", "Lille", "FRA"],
    ["Axel Witsel", "MF", "Girona", "MAR"],
    ["Kevin De Bruyne", "MF", "Napoli", "ITA"],
    ["Youri Tielemans", "MF", "Aston Villa", "ENG"],
    ["Diego Moreira", "MF", "Strasbourg", "PAR"],
    ["Hans Vanaken", "MF", "Club Brugge", "BEL"],
    ["Romelu Lukaku", "FW", "Napoli", "ITA"],
    ["Leandro Trossard", "FW", "Arsenal", "ENG"],
    ["Jérémy Doku", "FW", "Manchester City", "ENG"],
    ["Dodi Lukébakio", "FW", "Benfica", "POR"],
    ["Charles De Ketelaere", "FW", "Atalanta", "ITA"],
  ],
  EGY: [
    ["Mohamed El Shenawy", "GK", "Al Ahly", "EGY"],
    ["El Mahdy Soliman", "GK", "Zamalek", "EGY"],
    ["Mostafa Shobeir", "GK", "Al Ahly", "EGY"],
    ["Yasser Ibrahim", "DF", "Al Ahly", "EGY"],
    ["Mohamed Hany", "DF", "Al Ahly", "EGY"],
    ["Hossam Abdelmaguid", "DF", "Zamalek", "EGY"],
    ["Ramy Rabia", "DF", "Al Ain", "UAE"],
    ["Mohamed Abdelmonem", "DF", "Nice", "FRA"],
    ["Emam Ashour", "MF", "Al Ahly", "EGY"],
    ["Mostafa Ziko", "MF", "Pyramids", "EGY"],
    ["Hamdy Fathy", "MF", "Al-Wakrah", "QAT"],
    ["Mohanad Lasheen", "MF", "Pyramids", "EGY"],
    ["Nabil Emad", "MF", "Al-Najma", "KSA"],
    ["Trézéguet", "FW", "Al Ahly", "EGY"],
    ["Hamza Abdelkarim", "FW", "Barcelona B", "EGY"],
    ["Mohamed Salah", "FW", "Liverpool", "ENG"],
    ["Haissem Hassan", "FW", "Oviedo", "EGY"],
    ["Ibrahim Adel", "FW", "Nordsjælland", "EGY"],
  ],
  IRN: [
    ["Alireza Beiranvand", "GK", "Tractor", "IRN"],
    ["Payam Niazmand", "GK", "Persepolis", "IRN"],
    ["Hossein Hosseini", "GK", "Sepahan", "IRN"],
    ["Saleh Hardani", "DF", "Esteghlal", "IRN"],
    ["Ehsan Hajsafi", "DF", "Sepahan", "IRN"],
    ["Shojae Khalilzadeh", "DF", "Tractor", "IRN"],
    ["Milad Mohammadi", "DF", "Persepolis", "IRN"],
    ["Hossein Kanaanizadegan", "DF", "Persepolis", "IRN"],
    ["Saeid Ezatolahi", "MF", "Shabab Al Ahli", "UAE"],
    ["Alireza Jahanbakhsh", "MF", "Dender", "CAN"],
    ["Mohammad Mohebi", "MF", "Rostov", "RUS"],
    ["Saman Ghoddos", "MF", "Kalba", "IRN"],
    ["Rouzbeh Cheshmi", "MF", "Esteghlal", "IRN"],
    ["Mehdi Taremi", "FW", "Olympiacos", "GRE"],
    ["Mehdi Ghayedi", "FW", "Al Nasr", "UAE"],
    ["Ali Alipour", "FW", "Persepolis", "IRN"],
    ["Amirhossein Hosseinzadeh", "FW", "Tractor", "IRN"],
    ["Shahriyar Moghanlou", "FW", "Kalba", "IRN"],
  ],
  NZL: [
    ["Max Crocombe", "GK", "Millwall", "ENG"],
    ["Alex Paulsen", "GK", "Lechia Gdańsk", "NZL"],
    ["Michael Woud", "GK", "Auckland FC", "NZL"],
    ["Tim Payne", "DF", "Wellington Phoenix", "NZL"],
    ["Francis de Vries", "DF", "Auckland FC", "NZL"],
    ["Tyler Bindon", "DF", "Sheffield United", "ENG"],
    ["Michael Boxall", "DF", "Minnesota United FC", "USA"],
    ["Liberato Cacace", "DF", "Wrexham", "NZL"],
    ["Joe Bell", "MF", "Viking", "NZL"],
    ["Matthew Garbett", "MF", "Peterborough United", "NZL"],
    ["Marko Stamenić", "MF", "Swansea City", "WAL"],
    ["Sarpreet Singh", "MF", "Wellington Phoenix", "NZL"],
    ["Elijah Just", "MF", "Motherwell", "SCO"],
    ["Chris Wood", "FW", "Nottingham Forest", "ENG"],
    ["Kosta Barbarouses", "FW", "Western Sydney Wanderers", "NZL"],
    ["Ben Waine", "FW", "Port Vale", "NZL"],
    ["Jesse Randall", "FW", "Auckland FC", "NZL"],
    ["Alex Rufer", "MF", "Wellington Phoenix", "NZL"],
  ],
  ESP: [
    ["David Raya", "GK", "Arsenal", "ENG"],
    ["Joan Garcia", "GK", "Barcelona", "ESP"],
    ["Unai Simón", "GK", "Athletic Bilbao", "ESP"],
    ["Marc Pubill", "DF", "Atlético Madrid", "ESP"],
    ["Álex Grimaldo", "DF", "Bayer Leverkusen", "GER"],
    ["Eric García", "DF", "Barcelona", "ESP"],
    ["Marcos Llorente", "DF", "Atlético Madrid", "ESP"],
    ["Pedro Porro", "DF", "Tottenham Hotspur", "ENG"],
    ["Mikel Merino", "MF", "Arsenal", "ENG"],
    ["Fabián Ruiz", "MF", "Paris Saint-Germain", "FRA"],
    ["Gavi", "MF", "Barcelona", "ESP"],
    ["Álex Baena", "MF", "Atlético Madrid", "ESP"],
    ["Rodri", "MF", "Manchester City", "ENG"],
    ["Ferran Torres", "FW", "Barcelona", "ESP"],
    ["Dani Olmo", "FW", "Barcelona", "ESP"],
    ["Yéremy Pino", "FW", "Crystal Palace", "ENG"],
    ["Nico Williams", "FW", "Athletic Bilbao", "ESP"],
    ["Lamine Yamal", "FW", "Barcelona", "ESP"],
  ],
  CPV: [
    ["Vozinha", "GK", "Chaves", "CPV"],
    ["Márcio Rosa", "GK", "Montana", "CPV"],
    ["CJ dos Santos", "GK", "San Diego FC", "CPV"],
    ["Stopira", "DF", "Torreense", "CPV"],
    ["Diney", "DF", "Al Bataeh", "UAE"],
    ["Roberto Lopes", "DF", "Shamrock Rovers", "CPV"],
    ["Logan Costa", "DF", "Villarreal", "ESP"],
    ["Sidny Lopes Cabral", "DF", "Benfica", "POR"],
    ["Kevin Pina", "MF", "Krasnodar", "RUS"],
    ["Jovane Cabral", "MF", "Estrela Amadora", "CPV"],
    ["João Paulo", "MF", "FCSB", "CPV"],
    ["Jamiro Monteiro", "MF", "PEC Zwolle", "CUW"],
    ["Garry Rodrigues", "MF", "Apollon Limassol", "CPV"],
    ["Gilson Benchimol", "FW", "Akron Tolyatti", "CPV"],
    ["Dailon Livramento", "FW", "Casa Pia", "POR"],
    ["Ryan Mendes", "FW", "Iğdır", "CUW"],
    ["Deroy Duarte", "MF", "Ludogorets Razgrad", "CPV"],
    ["Laros Duarte", "MF", "Puskás Akadémia", "CPV"],
  ],
  KSA: [
    ["Nawaf Al-Aqidi", "GK", "Al-Nassr", "KSA"],
    ["Mohammed Al-Owais", "GK", "Al-Ula", "KSA"],
    ["Ahmed Al-Kassar", "GK", "Al-Qadsiah", "KSA"],
    ["Ali Majrashi", "DF", "Al-Ahli", "KSA"],
    ["Ali Lajami", "DF", "Al-Hilal", "KSA"],
    ["Abdulelah Al-Amri", "DF", "Al-Nassr", "KSA"],
    ["Hassan Al-Tambakti", "DF", "Al-Hilal", "KSA"],
    ["Saud Abdulhamid", "DF", "Lens", "FRA"],
    ["Nasser Al-Dawsari", "MF", "Al-Hilal", "KSA"],
    ["Musab Al-Juwayr", "MF", "Al-Qadsiah", "KSA"],
    ["Abdullah Al-Khaibari", "MF", "Al-Nassr", "KSA"],
    ["Ziyad Al-Johani", "MF", "Al-Ahli", "KSA"],
    ["Alaa Al-Hejji", "MF", "Neom", "KSA"],
    ["Ayman Yahya", "FW", "Al-Nassr", "KSA"],
    ["Firas Al-Buraikan", "FW", "Al-Ahli", "KSA"],
    ["Salem Al-Dawsari", "FW", "Al-Hilal", "KSA"],
    ["Saleh Al-Shehri", "FW", "Al-Ittihad", "KSA"],
    ["Khalid Al-Ghannam", "FW", "Al-Ettifaq", "KSA"],
  ],
  URU: [
    ["Sergio Rochet", "GK", "Internacional", "BRA"],
    ["Santiago Mele", "GK", "Monterrey", "MEX"],
    ["Fernando Muslera", "GK", "Estudiantes", "URU"],
    ["José María Giménez", "DF", "Atlético Madrid", "ESP"],
    ["Sebastián Cáceres", "DF", "América", "MEX"],
    ["Ronald Araújo", "DF", "Barcelona", "ESP"],
    ["Guillermo Varela", "DF", "Flamengo", "BRA"],
    ["Mathías Olivera", "DF", "Napoli", "ITA"],
    ["Manuel Ugarte", "MF", "Manchester United", "ENG"],
    ["Rodrigo Bentancur", "MF", "Tottenham Hotspur", "ENG"],
    ["Nicolás de la Cruz", "MF", "Flamengo", "BRA"],
    ["Federico Valverde", "MF", "Real Madrid", "ESP"],
    ["Giorgian de Arrascaeta", "MF", "Flamengo", "BRA"],
    ["Darwin Núñez", "FW", "Al-Hilal", "KSA"],
    ["Facundo Pellistri", "FW", "Panathinaikos", "GRE"],
    ["Brian Rodríguez", "FW", "América", "MEX"],
    ["Rodrigo Aguirre", "FW", "UANL", "URU"],
    ["Federico Viñas", "FW", "Oviedo", "EGY"],
  ],
  FRA: [
    ["Brice Samba", "GK", "Rennes", "FRA"],
    ["Mike Maignan", "GK", "Milan", "ITA"],
    ["Robin Risser", "GK", "Lens", "FRA"],
    ["Malo Gusto", "DF", "Chelsea", "ENG"],
    ["Lucas Digne", "DF", "Aston Villa", "ENG"],
    ["Dayot Upamecano", "DF", "Bayern Munich", "GER"],
    ["Jules Koundé", "DF", "Barcelona", "ESP"],
    ["Ibrahima Konaté", "DF", "Liverpool", "ENG"],
    ["Manu Koné", "MF", "Roma", "ITA"],
    ["Aurélien Tchouaméni", "MF", "Real Madrid", "ESP"],
    ["N\'Golo Kanté", "MF", "Fenerbahçe", "TUR"],
    ["Adrien Rabiot", "MF", "Milan", "ITA"],
    ["Warren Zaïre-Emery", "MF", "Paris Saint-Germain", "FRA"],
    ["Ousmane Dembélé", "FW", "Paris Saint-Germain", "FRA"],
    ["Marcus Thuram", "FW", "Inter Milan", "ITA"],
    ["Kylian Mbappé", "FW", "Real Madrid", "ESP"],
    ["Michael Olise", "FW", "Bayern Munich", "GER"],
    ["Bradley Barcola", "FW", "Paris Saint-Germain", "FRA"],
  ],
  SEN: [
    ["Yehvann Diouf", "GK", "Nice", "FRA"],
    ["Édouard Mendy", "GK", "Al-Ahli", "KSA"],
    ["Mory Diaw", "GK", "Le Havre", "FRA"],
    ["Mamadou Sarr", "DF", "Chelsea", "ENG"],
    ["Kalidou Koulibaly", "DF", "Al-Hilal", "KSA"],
    ["Abdoulaye Seck", "DF", "Maccabi Haifa", "CUW"],
    ["Ismail Jakobs", "DF", "Galatasaray", "TUR"],
    ["Krépin Diatta", "DF", "Monaco", "FRA"],
    ["Idrissa Gueye", "MF", "Everton", "ENG"],
    ["Pathé Ciss", "MF", "Rayo Vallecano", "ESP"],
    ["Lamine Camara", "MF", "Monaco", "FRA"],
    ["Pape Matar Sarr", "MF", "Tottenham Hotspur", "ENG"],
    ["Habib Diarra", "MF", "Sunderland", "ENG"],
    ["Assane Diao", "FW", "Como", "ITA"],
    ["Bamba Dieng", "FW", "Lorient", "FRA"],
    ["Sadio Mané", "FW", "Al-Nassr", "KSA"],
    ["Nicolas Jackson", "FW", "Bayern Munich", "GER"],
    ["Cherif Ndiaye", "FW", "Samsunspor", "SEN"],
  ],
  IRQ: [
    ["Fahad Talib", "GK", "Al-Talaba", "IRQ"],
    ["Jalal Hassan", "GK", "Al-Zawraa", "IRQ"],
    ["Ahmed Basil", "GK", "Al-Shorta", "IRQ"],
    ["Rebin Sulaka", "DF", "Port", "IRQ"],
    ["Hussein Ali", "DF", "Pogoń Szczecin", "IRQ"],
    ["Zaid Tahseen", "DF", "Pakhtakor", "UZB"],
    ["Akam Hashim", "DF", "Al-Zawraa", "IRQ"],
    ["Manaf Younis", "DF", "Al-Shorta", "IRQ"],
    ["Youssef Amyn", "MF", "AEK Larnaca", "CYP"],
    ["Ibrahim Bayesh", "MF", "Al Dhafra", "UAE"],
    ["Zidane Iqbal", "MF", "Utrecht", "IRQ"],
    ["Amir Al-Ammari", "MF", "Cracovia", "IRQ"],
    ["Kevin Yakob", "MF", "AGF", "IRQ"],
    ["Ali Al-Hamadi", "FW", "Luton Town", "IRQ"],
    ["Mohanad Ali", "FW", "Dibba", "IRQ"],
    ["Ahmed Qasem", "FW", "Nashville SC", "USA"],
    ["Ali Yousif", "FW", "Al-Talaba", "IRQ"],
    ["Ali Jasim", "FW", "Al-Najma", "KSA"],
  ],
  NOR: [
    ["Ørjan Nyland", "GK", "Sevilla", "ESP"],
    ["Sander Tangvik", "GK", "Hamburger SV", "GER"],
    ["Egil Selvik", "GK", "Watford", "ENG"],
    ["Kristoffer Ajer", "DF", "Brentford", "ENG"],
    ["Leo Østigård", "DF", "Genoa", "ITA"],
    ["David Møller Wolfe", "DF", "Wolverhampton Wanderers", "ENG"],
    ["Fredrik André Bjørkan", "DF", "Bodø/Glimt", "NOR"],
    ["Marcus Holmgren Pedersen", "DF", "Torino", "ITA"],
    ["Morten Thorsby", "MF", "Cremonese", "PAR"],
    ["Patrick Berg", "MF", "Bodø/Glimt", "NOR"],
    ["Sander Berge", "MF", "Fulham", "ENG"],
    ["Martin Ødegaard", "MF", "Arsenal", "ENG"],
    ["Fredrik Aursnes", "MF", "Benfica", "POR"],
    ["Alexander Sørloth", "FW", "Atlético Madrid", "ESP"],
    ["Erling Haaland", "FW", "Manchester City", "ENG"],
    ["Jørgen Strand Larsen", "FW", "Crystal Palace", "ENG"],
    ["Antonio Nusa", "FW", "RB Leipzig", "GER"],
    ["Julian Ryerson", "FW", "Borussia Dortmund", "GER"],
  ],
  ARG: [
    ["Juan Musso", "GK", "Atlético Madrid", "ESP"],
    ["Gerónimo Rulli", "GK", "Marseille", "FRA"],
    ["Emiliano Martínez", "GK", "Aston Villa", "ENG"],
    ["Marcos Senesi", "DF", "Bournemouth", "ENG"],
    ["Nicolás Tagliafico", "DF", "Lyon", "FRA"],
    ["Gonzalo Montiel", "DF", "River Plate", "ARG"],
    ["Lisandro Martínez", "DF", "Manchester United", "ENG"],
    ["Cristian Romero", "DF", "Tottenham Hotspur", "ENG"],
    ["Leandro Paredes", "MF", "Boca Juniors", "ARG"],
    ["Rodrigo De Paul", "MF", "Inter Miami CF", "USA"],
    ["Valentín Barco", "MF", "Strasbourg", "PAR"],
    ["Giovani Lo Celso", "MF", "Real Betis", "ESP"],
    ["Exequiel Palacios", "MF", "Bayer Leverkusen", "GER"],
    ["Julián Alvarez", "FW", "Atlético Madrid", "ESP"],
    ["Lionel Messi", "FW", "Inter Miami CF", "USA"],
    ["Thiago Almada", "FW", "Atlético Madrid", "ESP"],
    ["Giuliano Simeone", "FW", "Atlético Madrid", "ESP"],
    ["Nico Paz", "FW", "Como", "ITA"],
  ],
  ALG: [
    ["Melvin Mastil", "GK", "Stade Nyonnais", "ALG"],
    ["Oussama Benbot", "GK", "USM Alger", "ALG"],
    ["Luca Zidane", "GK", "Granada", "ALG"],
    ["Aïssa Mandi", "DF", "Lille", "FRA"],
    ["Achref Abada", "DF", "USM Alger", "ALG"],
    ["Mohamed Amine Tougai", "DF", "Espérance de Tunis", "ALG"],
    ["Zineddine Belaïd", "DF", "JS Kabylie", "ALG"],
    ["Jaouen Hadjam", "DF", "Young Boys", "SUI"],
    ["Ramiz Zerrouki", "MF", "Twente", "NED"],
    ["Houssem Aouar", "MF", "Al-Ittihad", "KSA"],
    ["Farès Chaïbi", "MF", "Eintracht Frankfurt", "GER"],
    ["Hicham Boudaoui", "MF", "Nice", "FRA"],
    ["Nabil Bentaleb", "MF", "Lille", "FRA"],
    ["Riyad Mahrez", "FW", "Al-Ahli", "KSA"],
    ["Amine Gouiri", "FW", "Marseille", "FRA"],
    ["Anis Hadj Moussa", "FW", "Feyenoord", "NED"],
    ["Nadhir Benbouali", "FW", "Győri ETO", "ALG"],
    ["Mohamed Amoura", "FW", "VfL Wolfsburg", "GER"],
  ],
  AUT: [
    ["Alexander Schlager", "GK", "Red Bull Salzburg", "AUT"],
    ["Florian Wiegele", "GK", "Viktoria Plzeň", "CZE"],
    ["Patrick Pentz", "GK", "Brøndby", "BIH"],
    ["David Affengruber", "DF", "Elche", "AUT"],
    ["Kevin Danso", "DF", "Tottenham Hotspur", "ENG"],
    ["Stefan Posch", "DF", "Mainz 05", "GER"],
    ["David Alaba", "DF", "Real Madrid", "ESP"],
    ["Philipp Lienhart", "DF", "SC Freiburg", "GER"],
    ["Xaver Schlager", "MF", "RB Leipzig", "GER"],
    ["Nicolas Seiwald", "MF", "RB Leipzig", "GER"],
    ["Marcel Sabitzer", "MF", "Borussia Dortmund", "GER"],
    ["Florian Grillitsch", "MF", "Braga", "POR"],
    ["Carney Chukwuemeka", "MF", "Borussia Dortmund", "GER"],
    ["Marko Arnautović", "FW", "Red Star Belgrade", "SRB"],
    ["Michael Gregoritsch", "FW", "FC Augsburg", "TUN"],
    ["Saša Kalajdžić", "FW", "LASK", "AUT"],
    ["Patrick Wimmer", "FW", "VfL Wolfsburg", "GER"],
    ["Phillipp Mwene", "DF", "Mainz 05", "GER"],
  ],
  JOR: [
    ["Yazeed Abulaila", "GK", "Al-Hussein", "JOR"],
    ["Nour Bani Attiah", "GK", "Al-Faisaly", "JOR"],
    ["Abdallah Al-Fakhouri", "GK", "Al-Wehdat", "JOR"],
    ["Mohammad Abu Hashish", "DF", "Al-Karma", "JOR"],
    ["Abdallah Nasib", "DF", "Al-Zawraa", "IRQ"],
    ["Husam Abu Dahab", "DF", "Al-Faisaly", "JOR"],
    ["Yazan Al-Arab", "DF", "FC Seoul", "JOR"],
    ["Mo Abualnadi", "DF", "Selangor", "JOR"],
    ["Amer Jamous", "MF", "Al-Zawraa", "IRQ"],
    ["Noor Al-Rawabdeh", "MF", "Selangor", "JOR"],
    ["Rajaei Ayed", "MF", "Al-Hussein", "JOR"],
    ["Ibrahim Sadeh", "MF", "Al-Karma", "JOR"],
    ["Mohammad Taha", "MF", "Al-Hussein", "JOR"],
    ["Mohammad Abu Zrayq", "FW", "Raja Casablanca", "JOR"],
    ["Ali Olwan", "FW", "Al-Sailiya", "JOR"],
    ["Musa Al-Taamari", "FW", "Rennes", "FRA"],
    ["Odeh Al-Fakhouri", "FW", "Pyramids", "EGY"],
    ["Mahmoud Al-Mardi", "FW", "Al-Hussein", "JOR"],
  ],
  POR: [
    ["Diogo Costa", "GK", "Porto", "POR"],
    ["José Sá", "GK", "Wolverhampton Wanderers", "ENG"],
    ["Rui Silva", "GK", "Sporting CP", "POR"],
    ["Nélson Semedo", "DF", "Fenerbahçe", "TUR"],
    ["Rúben Dias", "DF", "Manchester City", "ENG"],
    ["Tomás Araújo", "DF", "Benfica", "POR"],
    ["Diogo Dalot", "DF", "Manchester United", "ENG"],
    ["Renato Veiga", "DF", "Villarreal", "ESP"],
    ["Matheus Nunes", "MF", "Manchester City", "ENG"],
    ["Bruno Fernandes", "MF", "Manchester United", "ENG"],
    ["Bernardo Silva", "MF", "Manchester City", "ENG"],
    ["João Neves", "MF", "Paris Saint-Germain", "FRA"],
    ["Rúben Neves", "MF", "Al-Hilal", "KSA"],
    ["Cristiano Ronaldo", "FW", "Al-Nassr", "KSA"],
    ["Gonçalo Ramos", "FW", "Paris Saint-Germain", "FRA"],
    ["João Félix", "FW", "Al-Nassr", "KSA"],
    ["Francisco Trincão", "FW", "Sporting CP", "POR"],
    ["Rafael Leão", "FW", "Milan", "ITA"],
  ],
  DRC: [
    ["Lionel Mpasi", "GK", "Le Havre", "FRA"],
    ["Timothy Fayulu", "GK", "Noah", "DRC"],
    ["Matthieu Epolo", "GK", "Standard Liège", "BEL"],
    ["Aaron Wan-Bissaka", "DF", "West Ham United", "ENG"],
    ["Steve Kapuadi", "DF", "Widzew Łódź", "DRC"],
    ["Axel Tuanzebe", "DF", "Burnley", "ENG"],
    ["Dylan Batubinsika", "DF", "AEL", "DRC"],
    ["Joris Kayembe", "DF", "Genk", "BEL"],
    ["Ngal\'ayel Mukau", "MF", "Lille", "FRA"],
    ["Nathanaël Mbuku", "MF", "Montpellier", "FRA"],
    ["Samuel Moutoussamy", "MF", "Atromitos", "DRC"],
    ["Théo Bongonda", "MF", "Spartak Moscow", "DRC"],
    ["Noah Sadiki", "MF", "Sunderland", "ENG"],
    ["Brian Cipenga", "FW", "Castellón", "AUS"],
    ["Gaël Kakuta", "FW", "AEL", "DRC"],
    ["Meschak Elia", "FW", "Alanyaspor", "DRC"],
    ["Cédric Bakambu", "FW", "Real Betis", "ESP"],
    ["Fiston Mayele", "FW", "Pyramids", "EGY"],
  ],
  UZB: [
    ["Utkir Yusupov", "GK", "Navbahor Namangan", "UZB"],
    ["Abduvohid Nematov", "GK", "Nasaf", "UZB"],
    ["Botirali Ergashev", "GK", "Neftchi Fergana", "UZB"],
    ["Abdukodir Khusanov", "DF", "Manchester City", "ENG"],
    ["Khojiakbar Alijonov", "DF", "Pakhtakor", "UZB"],
    ["Farrukh Sayfiev", "DF", "Neftchi Fergana", "UZB"],
    ["Rustam Ashurmatov", "DF", "Esteghlal", "IRN"],
    ["Sherzod Nasrullaev", "DF", "Nasaf", "UZB"],
    ["Akmal Mozgovoy", "MF", "Pakhtakor", "UZB"],
    ["Otabek Shukurov", "MF", "Baniyas", "UAE"],
    ["Jamshid Iskanderov", "MF", "Neftchi Fergana", "UZB"],
    ["Odiljon Hamrobekov", "MF", "Tractor", "IRN"],
    ["Jaloliddin Masharipov", "MF", "Esteghlal", "IRN"],
    ["Eldor Shomurodov", "FW", "İstanbul Başakşehir", "TUR"],
    ["Azizbek Amonov", "FW", "Dinamo Samarqand", "UZB"],
    ["Igor Sergeev", "FW", "Persepolis", "IRN"],
    ["Oston Urunov", "MF", "Persepolis", "IRN"],
    ["Umar Eshmurodov", "DF", "Nasaf", "UZB"],
  ],
  COL: [
    ["David Ospina", "GK", "Atlético Nacional", "COL"],
    ["Camilo Vargas", "GK", "Atlas", "MEX"],
    ["Álvaro Montero", "GK", "Vélez Sarsfield", "COL"],
    ["Daniel Muñoz", "DF", "Crystal Palace", "ENG"],
    ["Jhon Lucumí", "DF", "Bologna", "ITA"],
    ["Santiago Arias", "DF", "Independiente", "PAN"],
    ["Yerry Mina", "DF", "Cagliari", "ITA"],
    ["Gustavo Puerta", "DF", "Racing Santander", "COL"],
    ["Kevin Castaño", "MF", "River Plate", "ARG"],
    ["Richard Ríos", "MF", "Benfica", "POR"],
    ["Jorge Carrascal", "MF", "Flamengo", "BRA"],
    ["James Rodríguez", "MF", "Minnesota United FC", "USA"],
    ["Jhon Arias", "MF", "Palmeiras", "BRA"],
    ["Luis Díaz", "FW", "Bayern Munich", "GER"],
    ["Jhon Córdoba", "FW", "Krasnodar", "RUS"],
    ["Cucho Hernández", "FW", "Real Betis", "ESP"],
    ["Jaminton Campaz", "FW", "Rosario Central", "COL"],
    ["Luis Suárez", "FW", "Sporting CP", "POR"],
  ],
  ENG: [
    ["Jordan Pickford", "GK", "Everton", "ENG"],
    ["Dean Henderson", "GK", "Crystal Palace", "ENG"],
    ["James Trafford", "GK", "Manchester City", "ENG"],
    ["Ezri Konsa", "DF", "Aston Villa", "ENG"],
    ["Nico O\'Reilly", "DF", "Manchester City", "ENG"],
    ["John Stones", "DF", "Manchester City", "ENG"],
    ["Marc Guéhi", "DF", "Manchester City", "ENG"],
    ["Tino Livramento", "DF", "Newcastle United", "ENG"],
    ["Declan Rice", "MF", "Arsenal", "ENG"],
    ["Elliot Anderson", "MF", "Nottingham Forest", "ENG"],
    ["Jude Bellingham", "MF", "Real Madrid", "ESP"],
    ["Jordan Henderson", "MF", "Brentford", "ENG"],
    ["Kobbie Mainoo", "MF", "Manchester United", "ENG"],
    ["Bukayo Saka", "FW", "Arsenal", "ENG"],
    ["Harry Kane", "FW", "Bayern Munich", "GER"],
    ["Marcus Rashford", "FW", "Barcelona", "ESP"],
    ["Anthony Gordon", "FW", "Newcastle United", "ENG"],
    ["Ollie Watkins", "FW", "Aston Villa", "ENG"],
  ],
  CRO: [
    ["Dominik Livaković", "GK", "Dinamo Zagreb", "CRO"],
    ["Ivor Pandur", "GK", "Hull City", "ENG"],
    ["Dominik Kotarski", "GK", "Copenhagen", "DEN"],
    ["Josip Stanišić", "DF", "Bayern Munich", "GER"],
    ["Marin Pongračić", "DF", "Fiorentina", "ITA"],
    ["Joško Gvardiol", "DF", "Manchester City", "ENG"],
    ["Duje Ćaleta-Car", "DF", "Real Sociedad", "ESP"],
    ["Josip Šutalo", "DF", "Ajax", "NED"],
    ["Nikola Moro", "MF", "Bologna", "ITA"],
    ["Mateo Kovačić", "MF", "Manchester City", "ENG"],
    ["Luka Modrić", "MF", "Milan", "ITA"],
    ["Nikola Vlašić", "MF", "Torino", "ITA"],
    ["Mario Pašalić", "MF", "Atalanta", "ITA"],
    ["Andrej Kramarić", "FW", "TSG Hoffenheim", "GER"],
    ["Ante Budimir", "FW", "Osasuna", "CRO"],
    ["Ivan Perišić", "FW", "PSV Eindhoven", "NED"],
    ["Igor Matanović", "FW", "SC Freiburg", "GER"],
    ["Marco Pašalić", "FW", "Orlando City SC", "USA"],
  ],
  GHA: [
    ["Lawrence Ati-Zigi", "GK", "St. Gallen", "SUI"],
    ["Joseph Anang", "GK", "St Patrick\'s Athletic", "GHA"],
    ["Benjamin Asare", "GK", "Hearts of Oak", "GHA"],
    ["Alidu Seidu", "DF", "Rennes", "FRA"],
    ["Jonas Adjetey", "DF", "VfL Wolfsburg", "GER"],
    ["Abdul Mumin", "DF", "Rayo Vallecano", "ESP"],
    ["Gideon Mensah", "DF", "Auxerre", "FRA"],
    ["Abdul Rahman Baba", "DF", "PAOK", "GRE"],
    ["Caleb Yirenkyi", "MF", "Nordsjælland", "EGY"],
    ["Thomas Partey", "MF", "Villarreal", "ESP"],
    ["Kwasi Sibo", "MF", "Oviedo", "EGY"],
    ["Antoine Semenyo", "MF", "Manchester City", "ENG"],
    ["Elisha Owusu", "MF", "Auxerre", "FRA"],
    ["Abdul Fatawu", "FW", "Leicester City", "ENG"],
    ["Jordan Ayew", "FW", "Leicester City", "ENG"],
    ["Brandon Thomas-Asante", "FW", "Coventry City", "ENG"],
    ["Christopher Bonsu Baah", "FW", "Al-Qadsiah", "KSA"],
    ["Iñaki Williams", "FW", "Athletic Bilbao", "ESP"],
  ],
  PAN: [
    ["Luis Mejía", "GK", "Nacional", "URU"],
    ["César Samudio", "GK", "Marathón", "PAN"],
    ["Orlando Mosquera", "GK", "Al-Fayha", "KSA"],
    ["César Blackman", "DF", "Slovan Bratislava", "PAN"],
    ["José Córdoba", "DF", "Norwich City", "ENG"],
    ["Fidel Escobar", "DF", "Saprissa", "PAN"],
    ["Edgardo Fariña", "DF", "Pari Nizhny Novgorod", "PAN"],
    ["Jiovany Ramos", "DF", "Puerto Cabello", "PAN"],
    ["Cristian Martínez", "MF", "Ironi Kiryat Shmona", "PAN"],
    ["José Luis Rodríguez", "MF", "Juárez", "PAN"],
    ["Adalberto Carrasquilla", "MF", "UNAM", "PAN"],
    ["Ismael Díaz", "MF", "León", "MEX"],
    ["Yoel Bárcenas", "MF", "Mazatlán", "MEX"],
    ["Tomás Rodríguez", "FW", "Saprissa", "PAN"],
    ["José Fajardo", "FW", "Universidad Católica", "PAN"],
    ["Cecilio Waterman", "FW", "Universidad de Concepción", "PAN"],
    ["Azarias Londoño", "FW", "Universidad Católica", "PAN"],
    ["Carlos Harvey", "DF", "Minnesota United FC", "USA"],
  ],
};
