-- Seed: player rosters for 48 WC 2026 group-phase teams
-- Generated by: node scripts/generate-players-seed.mjs
-- Approach: FIFA squads where available; otherwise key national-team players (2024–2026 cycle)
DELETE FROM public.tournament_predictions WHERE top_scorer_player_id IS NOT NULL;
DELETE FROM public.tournament_results WHERE top_scorer_player_id IS NOT NULL;
DELETE FROM public.players WHERE id_team IN (
  SELECT id_team FROM public.teams WHERE id_group IS NOT NULL
);

INSERT INTO public.players (id_team, name, position, club, club_country)
SELECT t.id_team, p.name, p.position, p.club, p.club_country
FROM public.teams t
CROSS JOIN (
  VALUES
  ('Guillermo Ochoa', 'GK', 'Salernitana', 'ITA'),
  ('Luis Malagón', 'GK', 'América', 'MEX'),
  ('Jorge Sánchez', 'DF', 'Ajax', 'NED'),
  ('César Montes', 'DF', 'Almería', 'ESP'),
  ('Johan Vásquez', 'DF', 'Genoa', 'ITA'),
  ('Gerardo Arteaga', 'DF', 'Monterrey', 'MEX'),
  ('Luis Chávez', 'MF', 'Dynamo Moscow', 'RUS'),
  ('Edson Álvarez', 'MF', 'West Ham', 'ENG'),
  ('Orbelín Pineda', 'MF', 'AEK Athens', 'GRE'),
  ('Luis Quiñones', 'MF', 'Tigres', 'MEX'),
  ('Carlos Rodríguez', 'MF', 'Cruz Azul', 'MEX'),
  ('Uriel Antuna', 'FW', 'América', 'MEX'),
  ('Raúl Jiménez', 'FW', 'Fulham', 'ENG'),
  ('Santiago Giménez', 'FW', 'Feyenoord', 'NED'),
  ('Alexis Vega', 'FW', 'Toluca', 'MEX'),
  ('Henry Martín', 'FW', 'América', 'MEX'),
  ('Julián Quiñones', 'FW', 'América', 'MEX'),
  ('Roberto Alvarado', 'FW', 'Guadalajara', 'MEX')
) AS p(name, position, club, club_country)
WHERE t.code = 'MEX';


INSERT INTO public.players (id_team, name, position, club, club_country)
SELECT t.id_team, p.name, p.position, p.club, p.club_country
FROM public.teams t
CROSS JOIN (
  VALUES
  ('Ronwen Williams', 'GK', 'Mamelodi Sundowns', 'RSA'),
  ('Veli Mothwa', 'GK', 'AmaZulu', 'RSA'),
  ('Grant Kekana', 'DF', 'Mamelodi Sundowns', 'RSA'),
  ('Khuliso Mudau', 'DF', 'Mamelodi Sundowns', 'RSA'),
  ('Mothobi Mvala', 'DF', 'Mamelodi Sundowns', 'RSA'),
  ('Austin Ditseke', 'DF', 'TS Galaxy', 'RSA'),
  ('Teboho Mokoena', 'MF', 'Mamelodi Sundowns', 'RSA'),
  ('Sphephelo Sithole', 'MF', 'AmaZulu', 'RSA'),
  ('Thapelo Maseko', 'MF', 'Mamelodi Sundowns', 'RSA'),
  ('Themba Zwane', 'MF', 'Mamelodi Sundowns', 'RSA'),
  ('Percy Tau', 'FW', 'Al Ahly', 'EGY'),
  ('Evidence Makgopa', 'FW', 'Orlando Pirates', 'RSA'),
  ('Zakhele Lepasa', 'FW', 'Stellenbosch', 'RSA'),
  ('Lyle Foster', 'FW', 'Burnley', 'ENG'),
  ('Tashreeq Matthews', 'FW', 'Cape Town City', 'RSA'),
  ('Thapelo Masilela', 'MF', 'SuperSport United', 'RSA'),
  ('Sphelele Mkhulise', 'MF', 'Mamelodi Sundowns', 'RSA'),
  ('Mothusi Maseko', 'FW', 'SuperSport United', 'RSA')
) AS p(name, position, club, club_country)
WHERE t.code = 'RSA';


INSERT INTO public.players (id_team, name, position, club, club_country)
SELECT t.id_team, p.name, p.position, p.club, p.club_country
FROM public.teams t
CROSS JOIN (
  VALUES
  ('Jo Hyeon-woo', 'GK', 'Ulsan HD', 'KOR'),
  ('Kim Seung-gyu', 'GK', 'Al-Shabab', 'KSA'),
  ('Kim Min-jae', 'DF', 'Bayern Munich', 'GER'),
  ('Kim Young-gwon', 'DF', 'Ulsan HD', 'KOR'),
  ('Jung Seung-hyun', 'DF', 'Ulsan HD', 'KOR'),
  ('Hong Hyun-seok', 'MF', 'Genk', 'BEL'),
  ('Lee Kang-in', 'MF', 'Paris Saint-Germain', 'FRA'),
  ('Hwang In-beom', 'MF', 'Feyenoord', 'NED'),
  ('Paik Seung-ho', 'MF', 'Birmingham City', 'ENG'),
  ('Son Heung-min', 'FW', 'Tottenham', 'ENG'),
  ('Hwang Hee-chan', 'FW', 'Wolverhampton', 'ENG'),
  ('Cho Gue-sung', 'FW', 'Midtjylland', 'DEN'),
  ('Oh Hyeon-gyu', 'FW', 'Genk', 'BEL'),
  ('Jeong Woo-yeong', 'FW', 'Stuttgart', 'GER'),
  ('Yang Hyun-jun', 'FW', 'Celtic', 'SCO'),
  ('Kim Jin-su', 'DF', 'Jeonbuk', 'KOR'),
  ('Lee Jae-sung', 'MF', 'Mainz', 'GER'),
  ('Moon Seon-min', 'FW', 'Jeonbuk', 'KOR')
) AS p(name, position, club, club_country)
WHERE t.code = 'KOR';


INSERT INTO public.players (id_team, name, position, club, club_country)
SELECT t.id_team, p.name, p.position, p.club, p.club_country
FROM public.teams t
CROSS JOIN (
  VALUES
  ('Tomáš Vaclík', 'GK', 'Basel', 'SUI'),
  ('Jiří Pavlenka', 'GK', 'Union Berlin', 'GER'),
  ('Vladimír Coufal', 'DF', 'West Ham', 'ENG'),
  ('David Hovorka', 'DF', 'Slavia Prague', 'CZE'),
  ('Ondřej Kúdela', 'DF', 'Slavia Prague', 'CZE'),
  ('Tomáš Souček', 'MF', 'West Ham', 'ENG'),
  ('Antonín Barák', 'MF', 'Fiorentina', 'ITA'),
  ('Alex Král', 'MF', 'Union Berlin', 'GER'),
  ('Lukáš Provod', 'MF', 'Slavia Prague', 'CZE'),
  ('Michal Sadílek', 'MF', 'Twente', 'NED'),
  ('Patrik Schick', 'FW', 'Bayer Leverkusen', 'GER'),
  ('Jan Kuchta', 'FW', 'Sparta Prague', 'CZE'),
  ('Adam Hložek', 'FW', 'Bayer Leverkusen', 'GER'),
  ('Václav Jurečka', 'FW', 'Slavia Prague', 'CZE'),
  ('Tomáš Chorý', 'FW', 'Slavia Prague', 'CZE'),
  ('David Doudera', 'DF', 'Slavia Prague', 'CZE'),
  ('Jaroslav Zelený', 'DF', 'Slavia Prague', 'CZE'),
  ('Lukáš Cerv', 'MF', 'Viktoria Plzeň', 'CZE')
) AS p(name, position, club, club_country)
WHERE t.code = 'CZE';


INSERT INTO public.players (id_team, name, position, club, club_country)
SELECT t.id_team, p.name, p.position, p.club, p.club_country
FROM public.teams t
CROSS JOIN (
  VALUES
  ('Milan Borjan', 'GK', 'Red Star Belgrade', 'SRB'),
  ('Maxime Crépeau', 'GK', 'Portland Timbers', 'USA'),
  ('Alphonso Davies', 'DF', 'Bayern Munich', 'GER'),
  ('Sam Adekugbe', 'DF', 'Hatayspor', 'TUR'),
  ('Derek Cornelius', 'DF', 'Marseille', 'FRA'),
  ('Richie Laryea', 'DF', 'Toronto FC', 'CAN'),
  ('Samuel Piette', 'MF', 'CF Montréal', 'CAN'),
  ('Stephen Eustáquio', 'MF', 'Porto', 'POR'),
  ('Jonathan Osorio', 'MF', 'Toronto FC', 'CAN'),
  ('Atiba Hutchinson', 'MF', 'İstanbul Başakşehir', 'TUR'),
  ('Alphonso Davies', 'MF', 'Bayern Munich', 'GER'),
  ('Jonathan David', 'FW', 'Lille', 'FRA'),
  ('Cyle Larin', 'FW', 'Mallorca', 'ESP'),
  ('Liam Millar', 'FW', 'Preston North End', 'ENG'),
  ('Tajon Buchanan', 'FW', 'Inter Milan', 'ITA'),
  ('Jacob Shaffelburg', 'FW', 'Nashville SC', 'USA'),
  ('Lucas Cavallini', 'FW', 'Vancouver Whitecaps', 'CAN'),
  ('Junior Hoilett', 'FW', 'Reading', 'ENG')
) AS p(name, position, club, club_country)
WHERE t.code = 'CAN';


INSERT INTO public.players (id_team, name, position, club, club_country)
SELECT t.id_team, p.name, p.position, p.club, p.club_country
FROM public.teams t
CROSS JOIN (
  VALUES
  ('Ibrahim Sehic', 'GK', 'Konyaspor', 'TUR'),
  ('Kenan Piric', 'GK', 'AEK Larnaca', 'CYP'),
  ('Sead Kolašinac', 'DF', 'Marseille', 'FRA'),
  ('Stjepan Lončar', 'DF', 'Rijeka', 'CRO'),
  ('Adis Jahović', 'DF', 'Sarajevo', 'BIH'),
  ('Miralem Pjanić', 'MF', 'Sharjah', 'UAE'),
  ('Rade Krunić', 'MF', 'Genoa', 'ITA'),
  ('Amir Hadžiahmetović', 'MF', 'Konyaspor', 'TUR'),
  ('Edin Džeko', 'FW', 'Fenerbahçe', 'TUR'),
  ('Ermedin Demirović', 'FW', 'Stuttgart', 'GER'),
  ('Miroslav Stevanović', 'FW', 'Servette', 'SUI'),
  ('Benjamin Tahirović', 'FW', 'Hoffenheim', 'GER'),
  ('Elvis Sarić', 'MF', 'Lech Poznań', 'POL'),
  ('Anel Ahmedhodžić', 'DF', 'Sheffield United', 'ENG'),
  ('Dennis Hadžikadunić', 'DF', 'Rostov', 'RUS'),
  ('Edin Višća', 'FW', 'Trabzonspor', 'TUR'),
  ('Mario Kvesić', 'MF', 'Kayserispor', 'TUR'),
  ('Admir Lulić', 'MF', 'Sarajevo', 'BIH')
) AS p(name, position, club, club_country)
WHERE t.code = 'BIH';


INSERT INTO public.players (id_team, name, position, club, club_country)
SELECT t.id_team, p.name, p.position, p.club, p.club_country
FROM public.teams t
CROSS JOIN (
  VALUES
  ('Saad Al-Sheeb', 'GK', 'Al-Sadd', 'QAT'),
  ('Mishal Barsham', 'GK', 'Al-Sadd', 'QAT'),
  ('Abdelkarim Hassan', 'DF', 'Al-Sadd', 'QAT'),
  ('Boualem Khoukhi', 'DF', 'Al-Sadd', 'QAT'),
  ('Pedro Miguel', 'DF', 'Al-Sadd', 'QAT'),
  ('Homam Ahmed', 'DF', 'Al-Gharafa', 'QAT'),
  ('Assim Madibo', 'MF', 'Al-Wakrah', 'QAT'),
  ('Hassan Al-Haydos', 'MF', 'Al-Sadd', 'QAT'),
  ('Akram Afif', 'FW', 'Al-Sadd', 'QAT'),
  ('Almoez Ali', 'FW', 'Al-Duhail', 'QAT'),
  ('Mohammed Muntari', 'FW', 'Al-Duhail', 'QAT'),
  ('Yusuf Abdurisag', 'FW', 'Al-Arabi', 'QAT'),
  ('Karim Boudiaf', 'MF', 'Al-Duhail', 'QAT'),
  ('Ahmed Alaaeldin', 'FW', 'Al-Gharafa', 'QAT'),
  ('Mohammed Waad', 'MF', 'Al-Sadd', 'QAT'),
  ('Tarek Salman', 'DF', 'Al-Sadd', 'QAT'),
  ('Bassam Al-Rawi', 'DF', 'Al-Rayyan', 'QAT'),
  ('Ahmed Fadl', 'MF', 'Al-Arabi', 'QAT')
) AS p(name, position, club, club_country)
WHERE t.code = 'QAT';


INSERT INTO public.players (id_team, name, position, club, club_country)
SELECT t.id_team, p.name, p.position, p.club, p.club_country
FROM public.teams t
CROSS JOIN (
  VALUES
  ('Yann Sommer', 'GK', 'Inter Milan', 'ITA'),
  ('Gregor Kobel', 'GK', 'Borussia Dortmund', 'GER'),
  ('Manuel Akanji', 'DF', 'Manchester City', 'ENG'),
  ('Ricardo Rodríguez', 'DF', 'Torino', 'ITA'),
  ('Fabian Schär', 'DF', 'Newcastle United', 'ENG'),
  ('Silvan Widmer', 'DF', 'Mainz', 'GER'),
  ('Granit Xhaka', 'MF', 'Bayer Leverkusen', 'GER'),
  ('Remo Freuler', 'MF', 'Bologna', 'ITA'),
  ('Ruben Vargas', 'MF', 'Augsburg', 'GER'),
  ('Xherdan Shaqiri', 'MF', 'Chicago Fire', 'USA'),
  ('Breel Embolo', 'FW', 'Monaco', 'FRA'),
  ('Noah Okafor', 'FW', 'Milan', 'ITA'),
  ('Dan Ndoye', 'FW', 'Bologna', 'ITA'),
  ('Zeki Amdouni', 'FW', 'Burnley', 'ENG'),
  ('Michel Aebischer', 'MF', 'Bologna', 'ITA'),
  ('Denis Zakaria', 'MF', 'Monaco', 'FRA'),
  ('Vincent Sierro', 'MF', 'Toulouse', 'FRA'),
  ('Nico Elvedi', 'DF', 'Borussia Mönchengladbach', 'GER')
) AS p(name, position, club, club_country)
WHERE t.code = 'SUI';