-- WC 2026 poll engine (ported from Brasil 2014 MySQL → Postgres / Supabase)

-- Catalog
CREATE TABLE public.rounds (
  id_round smallint PRIMARY KEY,
  name_round text NOT NULL UNIQUE
);

CREATE TABLE public.groups (
  id_group smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_code char(1) NOT NULL UNIQUE CHECK (group_code ~ '^[A-L]$')
);

CREATE TABLE public.venues (
  id_venue smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  city text NOT NULL,
  stadium text NOT NULL
);

CREATE TABLE public.teams (
  id_team smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  country text NOT NULL UNIQUE,
  id_group smallint REFERENCES public.groups (id_group),
  code char(3) NOT NULL UNIQUE
);

-- Knockout bracket placeholders (Primero A, Ganador 49, Mejor Tercero X, etc.)
CREATE TABLE public.knockout_slots (
  id_slot smallint PRIMARY KEY,
  label text NOT NULL UNIQUE,
  resolved_team_id smallint REFERENCES public.teams (id_team)
);

-- FIFA third-place combination matrix (fill from official regulations)
CREATE TABLE public.third_place_matrix (
  id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scenario_key text NOT NULL UNIQUE,
  -- which groups supply the 8 best thirds (e.g. 'ABCDEFGH' pattern)
  qualifying_groups text NOT NULL,
  -- JSON map: match_slot -> placeholder label resolved via matrix
  slot_mappings jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE public.matches (
  id_match smallint PRIMARY KEY,
  id_round smallint NOT NULL REFERENCES public.rounds (id_round),
  id_group smallint REFERENCES public.groups (id_group),
  match_date date NOT NULL,
  match_time time NOT NULL,
  id_venue smallint NOT NULL REFERENCES public.venues (id_venue),
  home_team_id smallint NOT NULL REFERENCES public.teams (id_team),
  away_team_id smallint NOT NULL REFERENCES public.teams (id_team),
  home_slot_id smallint REFERENCES public.knockout_slots (id_slot),
  away_slot_id smallint REFERENCES public.knockout_slots (id_slot)
);

CREATE TABLE public.match_results (
  id_match smallint PRIMARY KEY REFERENCES public.matches (id_match) ON DELETE CASCADE,
  goals_home smallint,
  goals_away smallint,
  goals_home_et smallint,
  goals_away_et smallint,
  goals_home_pt smallint,
  goals_away_pt smallint,
  first_goal_minute smallint,
  first_goal_player_id smallint,
  pens_home smallint,
  pens_away smallint
);

CREATE TABLE public.players (
  id_player smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_team smallint NOT NULL REFERENCES public.teams (id_team),
  name text NOT NULL,
  position text,
  club text,
  club_country text
);

-- Scoring weights (was puntos_apuestas)
CREATE TABLE public.scoring_rules (
  id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rule_key text NOT NULL UNIQUE,
  points smallint NOT NULL DEFAULT 0
);

-- User domain (auth.users handled by Supabase Auth)
CREATE TABLE public.profiles (
  id uuid PRIMARY KEY REFERENCES auth.users (id) ON DELETE CASCADE,
  username text UNIQUE,
  first_name text NOT NULL,
  last_name text NOT NULL,
  favorite_team_id smallint REFERENCES public.teams (id_team),
  is_admin boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.pools (
  id_pool smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description text NOT NULL,
  owner_id uuid NOT NULL REFERENCES public.profiles (id) ON DELETE CASCADE,
  is_paid boolean NOT NULL DEFAULT false
);

CREATE TABLE public.predictions (
  id_pool smallint NOT NULL REFERENCES public.pools (id_pool) ON DELETE CASCADE,
  id_match smallint NOT NULL REFERENCES public.matches (id_match) ON DELETE CASCADE,
  goals_home smallint,
  goals_away smallint,
  goals_home_pt smallint,
  goals_away_pt smallint,
  extra_time boolean,
  first_goal_minute text CHECK (
    first_goal_minute IS NULL
    OR first_goal_minute IN (
      '0-15', '16-30', '31-45', '45+_1T',
      '46-60', '61-75', '76-90', '90+_2T'
    )
  ),
  PRIMARY KEY (id_pool, id_match)
);

-- Indexes
CREATE INDEX idx_matches_round ON public.matches (id_round);
CREATE INDEX idx_matches_group ON public.matches (id_group);
CREATE INDEX idx_teams_group ON public.teams (id_group);
CREATE INDEX idx_predictions_match ON public.predictions (id_match);

-- RLS
ALTER TABLE public.rounds ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.venues ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.teams ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.knockout_slots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.third_place_matrix ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.matches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.match_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.players ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.scoring_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pools ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.predictions ENABLE ROW LEVEL SECURITY;

-- Public read for tournament data
CREATE POLICY "Public read rounds" ON public.rounds FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Public read groups" ON public.groups FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Public read venues" ON public.venues FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Public read teams" ON public.teams FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Public read matches" ON public.matches FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Public read match_results" ON public.match_results FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Public read players" ON public.players FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Public read scoring_rules" ON public.scoring_rules FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Public read knockout_slots" ON public.knockout_slots FOR SELECT TO anon, authenticated USING (true);

-- Profiles: own row
CREATE POLICY "Profiles select own" ON public.profiles FOR SELECT TO authenticated USING (auth.uid() = id);
CREATE POLICY "Profiles insert own" ON public.profiles FOR INSERT TO authenticated WITH CHECK (auth.uid() = id);
CREATE POLICY "Profiles update own" ON public.profiles FOR UPDATE TO authenticated USING (auth.uid() = id) WITH CHECK (auth.uid() = id);

-- Pools
CREATE POLICY "Pools select all authenticated" ON public.pools FOR SELECT TO authenticated USING (true);
CREATE POLICY "Pools insert own" ON public.pools FOR INSERT TO authenticated WITH CHECK (owner_id = auth.uid());
CREATE POLICY "Pools update own" ON public.pools FOR UPDATE TO authenticated USING (owner_id = auth.uid()) WITH CHECK (owner_id = auth.uid());

-- Predictions: only pool owner
CREATE POLICY "Predictions select own pool" ON public.predictions FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM public.pools p WHERE p.id_pool = predictions.id_pool AND p.owner_id = auth.uid()));
CREATE POLICY "Predictions insert own pool" ON public.predictions FOR INSERT TO authenticated
  WITH CHECK (EXISTS (SELECT 1 FROM public.pools p WHERE p.id_pool = predictions.id_pool AND p.owner_id = auth.uid()));
CREATE POLICY "Predictions update own pool" ON public.predictions FOR UPDATE TO authenticated
  USING (EXISTS (SELECT 1 FROM public.pools p WHERE p.id_pool = predictions.id_pool AND p.owner_id = auth.uid()))
  WITH CHECK (EXISTS (SELECT 1 FROM public.pools p WHERE p.id_pool = predictions.id_pool AND p.owner_id = auth.uid()));

-- Admin policies (match results, matrix) — service role or is_admin via security definer functions later
CREATE POLICY "Admins manage match_results" ON public.match_results FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM public.profiles pr WHERE pr.id = auth.uid() AND pr.is_admin = true))
  WITH CHECK (EXISTS (SELECT 1 FROM public.profiles pr WHERE pr.id = auth.uid() AND pr.is_admin = true));

CREATE POLICY "Admins manage third_place_matrix" ON public.third_place_matrix FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM public.profiles pr WHERE pr.id = auth.uid() AND pr.is_admin = true))
  WITH CHECK (EXISTS (SELECT 1 FROM public.profiles pr WHERE pr.id = auth.uid() AND pr.is_admin = true));

CREATE POLICY "Public read third_place_matrix" ON public.third_place_matrix FOR SELECT TO anon, authenticated USING (true);
